// The pgTAP suite's declared inventory: which files must run, and how many
// assertions each one must contribute.
//
// Why a manifest and not just "run whatever is in the directory"
// --------------------------------------------------------------
// The failure this repair addresses was diagnosed partly by comparing the two
// lanes: the shim lane reported "70 files, 2673 assertions" and the stack lane
// died silently at file 15. That comparison only worked because both lanes
// print a total. A total alone is still weak: a runner that quietly stopped
// globbing a file, or a partition scheme that dropped one, would simply report
// a smaller number that nobody was checking against anything.
//
// So the expected inventory is written down and checked on every run, in both
// lanes. Changing what the suite verifies is legitimate and common; doing it
// WITHOUT the diff showing a manifest change is what this makes impossible.
//
// Regenerate with:  npm run db:test -- --write-manifest    (psql lane)

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
export const ROOT = resolve(HERE, '..', '..');
export const TESTS_DIR = join(ROOT, 'supabase', 'tests');
export const MANIFEST_PATH = join(HERE, 'suite-manifest.json');

/**
 * The suite directory and manifest are overridable ONLY so the runner's own
 * self-proof (scripts/db/runner-proof.mjs) can drive it against a deliberately
 * broken miniature suite. CI never sets these.
 *
 * The override cannot weaken a real run: the manifest and the directory are
 * checked against each other, so pointing at a smaller directory without also
 * supplying a matching manifest fails the inventory check. The runner
 * additionally prints a banner and marks every summary line, so a CI log can
 * never claim the canonical suite passed when it ran something else.
 */
export function resolveSuitePaths(env = process.env) {
  const testsDir = env.DB_TEST_TESTS_DIR ? resolve(env.DB_TEST_TESTS_DIR) : TESTS_DIR;
  const manifestPath = env.DB_TEST_MANIFEST_PATH ? resolve(env.DB_TEST_MANIFEST_PATH) : MANIFEST_PATH;
  return {
    testsDir,
    manifestPath,
    overridden: testsDir !== TESTS_DIR || manifestPath !== MANIFEST_PATH,
  };
}

/** The files on disk, in the order every runner executes them. */
export function listTestFiles(dir = TESTS_DIR) {
  return readdirSync(dir).filter((name) => name.endsWith('.sql')).sort();
}

export function readManifest(path = MANIFEST_PATH) {
  const parsed = JSON.parse(readFileSync(path, 'utf8'));
  if (!parsed || typeof parsed !== 'object' || typeof parsed.files !== 'object' || parsed.files === null) {
    throw new Error(`${path} is not a suite manifest: expected an object with a "files" map`);
  }
  return parsed;
}

export function writeManifest(files, path = MANIFEST_PATH) {
  const ordered = Object.keys(files).sort();
  const body = {
    $comment:
      'Generated by `npm run db:test -- --write-manifest`. Both shadow-database lanes verify '
      + 'their run against this file, so a change here must accompany any change to the pgTAP suite.',
    totalAssertions: ordered.reduce((sum, name) => sum + files[name], 0),
    fileCount: ordered.length,
    files: Object.fromEntries(ordered.map((name) => [name, files[name]])),
  };
  writeFileSync(path, `${JSON.stringify(body, null, 2)}\n`);
  return body;
}

export function expectedTotal(manifest) {
  return Object.values(manifest.files).reduce((sum, count) => sum + count, 0);
}

const REGENERATE = 'run `npm run db:test -- --write-manifest` against the psql lane and commit the result';

/**
 * The inventory on disk must match the manifest exactly. This is the guard
 * against a file being silently dropped from (or smuggled into) the suite.
 */
export function checkInventory(manifest, files) {
  const expected = Object.keys(manifest.files).sort();
  const missing = expected.filter((name) => !files.includes(name));
  const unexpected = files.filter((name) => !expected.includes(name));
  const problems = [];
  if (missing.length > 0) {
    problems.push(`the manifest declares ${missing.length} file(s) that are not on disk: ${missing.join(', ')}`);
  }
  if (unexpected.length > 0) {
    problems.push(`${unexpected.length} test file(s) on disk are absent from the manifest: ${unexpected.join(', ')}`);
  }
  return { ok: problems.length === 0, problems: problems.map((p) => `${p} — ${REGENERATE}`) };
}

/**
 * Every declared file must have been executed exactly once, and each must have
 * produced exactly the declared number of assertions.
 *
 * Exact rather than a floor on purpose. A floor cannot see a swap — delete ten
 * assertions, add ten elsewhere — which is precisely how verification erodes
 * without anyone deciding to erode it.
 */
export function checkExecution(manifest, observed) {
  const problems = [];
  const expected = manifest.files;

  for (const [name, count] of Object.entries(expected)) {
    if (!(name in observed)) {
      problems.push(`${name} was declared in the manifest but never ran`);
      continue;
    }
    if (observed[name] !== count) {
      problems.push(`${name} produced ${observed[name]} assertions, manifest declares ${count}`);
    }
  }
  for (const name of Object.keys(observed)) {
    if (!(name in expected)) problems.push(`${name} ran but is not declared in the manifest`);
  }

  const observedTotal = Object.values(observed).reduce((sum, count) => sum + count, 0);
  const declaredTotal = expectedTotal(manifest);
  if (observedTotal !== declaredTotal) {
    problems.push(`the suite produced ${observedTotal} assertions, manifest declares ${declaredTotal}`);
  }

  return {
    ok: problems.length === 0,
    observedTotal,
    declaredTotal,
    problems: problems.map((p) => `${p} — if this change is intended, ${REGENERATE}`),
  };
}

/**
 * The Supabase lane runs pg_prove, which reports only a suite-level roll-up
 * ("Files=70, Tests=2673"). Check what it does report, and be explicit that
 * per-file counts were not available rather than pretending they matched.
 */
export function checkSummary(manifest, summary) {
  const problems = [];
  const declaredFiles = Object.keys(manifest.files).length;
  const declaredTotal = expectedTotal(manifest);
  if (!summary) {
    return {
      ok: false,
      problems: ['the runner produced no file/assertion summary, so no inventory claim can be verified'],
    };
  }
  if (summary.files !== declaredFiles) {
    problems.push(`the runner executed ${summary.files} files, manifest declares ${declaredFiles}`);
  }
  if (summary.tests !== declaredTotal) {
    problems.push(`the runner reported ${summary.tests} assertions, manifest declares ${declaredTotal}`);
  }
  return { ok: problems.length === 0, problems: problems.map((p) => `${p} — if this change is intended, ${REGENERATE}`) };
}
