// The database-to-TypeScript contract: where the generated types live, and how
// generated output is normalized before it is compared.
//
// Why normalization exists at all
// -------------------------------
// A drift guard that compares raw generator output is only as stable as the
// generator's incidental formatting. If the CLI ever adds a timestamp or a
// version banner, an unnormalized guard fails on every run and gets disabled --
// which is worse than having no guard.
//
// So normalization is deliberately NARROW and enumerated. It removes exactly
// the header shapes listed in STRIPPED_HEADER_PATTERNS and nothing else, and
// `describeNormalization` reports what it actually removed so a CI failure can
// never be blamed on invisible rewriting. It must never touch a type
// declaration: `assertNoDeclarationsRemoved` proves that on every call.

import { readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
export const ROOT = resolve(HERE, '..', '..');

/**
 * The single generated file. It lives in `shared/` rather than inside either
 * package because both the client and the server consume it, and a second copy
 * is exactly the drift this work order exists to remove.
 */
export const TYPES_PATH = join(ROOT, 'shared', 'database.types.ts');
export const TYPES_RELATIVE = 'shared/database.types.ts';

/**
 * Header lines the generator may or may not emit depending on its version and
 * on whether it detected a TTY. Each is anchored to the start of a line and
 * matched only within the leading comment block, never in the body.
 */
const STRIPPED_HEADER_PATTERNS = [
  { name: 'CLI version banner', re: /^\/\/\s*Generated by supabase CLI.*$/i },
  { name: 'generation timestamp', re: /^\/\/\s*Generated at .*$/i },
  { name: 'update notice', re: /^A new version of Supabase CLI is available.*$/i },
  { name: 'update recommendation', re: /^We recommend updating regularly.*$/i },
  { name: 'telemetry notice', re: /^\s*supabase telemetry disable\s*$/ },
];

/** A line that begins a TypeScript declaration. Normalization must never eat one. */
const DECLARATION = /^\s*(export\s+)?(type|interface|const|enum|declare|import)\b/;

export function assertNoDeclarationsRemoved(before, after) {
  // Compare with trailing whitespace already stripped: normalization is allowed
  // to remove that, so including it here would report every such line as lost.
  const declarations = (text) => text
    .split('\n')
    .map((line) => line.replace(/[ \t]+$/, ''))
    .filter((line) => DECLARATION.test(line));
  const survivors = new Set(declarations(after));
  const lost = declarations(before).filter((line) => !survivors.has(line));
  if (lost.length > 0) {
    throw new Error(
      `normalization removed ${lost.length} declaration line(s), which it must never do: `
      + lost.slice(0, 3).map((l) => JSON.stringify(l.trim())).join(', '),
    );
  }
}

/**
 * Normalize generated output for comparison and for writing.
 *
 * Returns { text, removed } where `removed` names every pattern that actually
 * matched, so the caller can print it rather than silently rewriting.
 */
export function normalizeGenerated(raw) {
  const removed = [];
  const lines = raw.replace(/\r\n/g, '\n').split('\n');
  const kept = [];

  for (const line of lines) {
    const hit = STRIPPED_HEADER_PATTERNS.find((pattern) => pattern.re.test(line));
    if (hit) {
      removed.push(hit.name);
      continue;
    }
    // Trailing whitespace is invisible in review and differs between shells.
    kept.push(line.replace(/[ \t]+$/, ''));
  }

  // Exactly one trailing newline, no leading blank lines.
  while (kept.length > 0 && kept[0].trim() === '') kept.shift();
  while (kept.length > 0 && kept[kept.length - 1].trim() === '') kept.pop();
  const text = `${kept.join('\n')}\n`;

  assertNoDeclarationsRemoved(raw, text);
  return { text, removed: [...new Set(removed)] };
}

export function describeNormalization(removed) {
  if (removed.length === 0) return 'normalization removed nothing beyond trailing whitespace';
  return `normalization removed known nondeterministic headers: ${removed.join(', ')}`;
}

/**
 * A generated file that is empty, truncated, or missing the Database interface
 * must never be written or accepted. A guard that happily records a zero-byte
 * "schema" is worse than no guard, because the next real drift compares clean.
 */
export function assertPlausiblyGenerated(text) {
  const problems = [];
  if (text.trim().length === 0) problems.push('the generator produced no output');
  if (!/export type Database\b|export interface Database\b/.test(text)) {
    problems.push('the output declares no `Database` type');
  }
  const tables = countMembers(text, 'Tables');
  if (tables < 50) {
    problems.push(
      `the output declares only ${tables} tables; the replayed schema has far more, `
      + 'so this is a truncated or partial generation rather than a schema that shrank',
    );
  }
  if (problems.length > 0) {
    throw new Error(`refusing to accept generated types — ${problems.join('; ')}`);
  }
  return { tables };
}

/**
 * Count the members of a top-level section (Tables/Views/Functions/Enums) in
 * generated output. Used for the coverage report and the plausibility floor.
 */
export function countMembers(text, section) {
  const start = text.indexOf(`      ${section}: {`);
  if (start < 0) return 0;
  const body = text.slice(start);
  const end = body.indexOf('\n      }');
  if (end < 0) return 0;
  return [...body.slice(0, end).matchAll(/^        ([A-Za-z_][A-Za-z0-9_]*): \{/gm)].length;
}

/** Section counts for the CI coverage line. */
export function summarize(text) {
  return {
    tables: countMembers(text, 'Tables'),
    views: countMembers(text, 'Views'),
    functions: countMembers(text, 'Functions'),
    enums: countEnums(text),
  };
}

function countEnums(text) {
  const start = text.indexOf('      Enums: {');
  if (start < 0) return 0;
  const body = text.slice(start);
  const end = body.indexOf('\n      }');
  if (end < 0) return 0;
  return [...body.slice(0, end).matchAll(/^        ([A-Za-z_][A-Za-z0-9_]*):/gm)].length;
}

export function readCommittedTypes(path = TYPES_PATH) {
  try {
    return readFileSync(path, 'utf8');
  } catch (error) {
    if (error.code === 'ENOENT') return null;
    throw error;
  }
}
