begin;
create extension if not exists pgtap with schema public;
select plan(18);
select has_function('public','observe_cycle_count_item',array['uuid','uuid','text','text','uuid','text'],'keyed item observation exists');
select has_function('public','observe_cycle_count_lot',array['uuid','uuid','text','integer','uuid','text'],'keyed lot observation exists');
select has_function('public','void_cycle_count_observation',array['uuid','uuid','uuid','text','text','uuid'],'keyed void exists');
select function_privs_are('public','observe_cycle_count_item',array['uuid','uuid','text','text','uuid','text'],'authenticated',array['EXECUTE'],'authenticated can call only the keyed item signature');
select function_privs_are('public','observe_cycle_count_lot',array['uuid','uuid','text','integer','uuid','text'],'authenticated',array['EXECUTE'],'authenticated can call only the keyed lot signature');
select function_privs_are('public','void_cycle_count_observation',array['uuid','uuid','uuid','text','text','uuid'],'authenticated',array['EXECUTE'],'authenticated can call only the keyed void signature');
select function_privs_are('public','observe_cycle_count_item',array['uuid','uuid','text','text','text'],'authenticated',array[]::text[],'legacy item observation is not executable');
select function_privs_are('public','observe_cycle_count_lot',array['uuid','uuid','text','integer','text'],'authenticated',array[]::text[],'legacy lot observation is not executable');
select function_privs_are('public','void_cycle_count_observation',array['uuid','uuid','text','text'],'authenticated',array[]::text[],'legacy void is not executable');
select is((select prosecdef from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='observe_cycle_count_item' and p.pronargs=6),true,'item observation is SECURITY DEFINER');
select is((select prosecdef from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='observe_cycle_count_lot' and p.pronargs=6),true,'lot observation is SECURITY DEFINER');
select is((select proconfig @> array['search_path=""'] from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='observe_cycle_count_item' and p.pronargs=6),true,'item observation pins search path');
select is((select proconfig @> array['search_path=""'] from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='observe_cycle_count_lot' and p.pronargs=6),true,'lot observation pins search path');
select has_index('public','cycle_count_item_observations','cycle_count_item_observation_idempotency','item keys are unique');
select has_index('public','cycle_count_lot_observations','cycle_count_lot_observation_idempotency','lot keys are unique');
select trigger_is('public','cycle_count_observation_attempts','cycle_count_observation_attempts_append_only','app.forbid_update_delete()','attempts are append-only');
select trigger_is('public','cycle_count_observation_idempotency','cycle_count_observation_idempotency_append_only','app.forbid_update_delete()','canonical keys are immutable');
select is((select count(*)::int from information_schema.routine_privileges where grantee='anon' and routine_schema='public' and routine_name in ('observe_cycle_count_item','observe_cycle_count_lot','void_cycle_count_observation')),0,'anon cannot execute observation mutations');
select * from finish();
rollback;
