begin; create extension if not exists pgtap with schema public; select plan(18);
select has_table('public','cycle_count_resolution_action_rules','resolution matrix is authoritative');
select has_table('public','cycle_count_resolution_attempts','resolution attempts are durable');
select has_table('public','cycle_count_resolution_attempt_events','attempt history is append-only');
select has_table('public','inventory_loss_events','loss provenance is durable');
select has_column('public','inventory_items','retirement_reason','loss is not described as voiding');
select has_function('public','create_cycle_count_resolution_attempt',array['uuid','uuid','text','text','text','uuid'],'attempt creation is a separate call');
select has_function('public','execute_cycle_count_resolution_attempt',array['uuid','uuid'],'attempt execution is a separate call');
select has_function('public','complete_cycle_count_latest',array['uuid','uuid','boolean','text'],'latest-result completion exists');
select function_privs_are('public','resolve_cycle_count_discrepancy',array['uuid','uuid','cycle_count_resolution_action','text','text'],'authenticated',array[]::text[],'legacy resolution is revoked');
select function_privs_are('public','complete_cycle_count',array['uuid','uuid','boolean','text'],'authenticated',array[]::text[],'legacy all-observation completion is revoked');
select trigger_is('public','inventory_loss_events','inventory_loss_events_append_only','app.forbid_update_delete()','loss events are append-only');
select trigger_is('public','cycle_count_resolution_attempt_events','cycle_count_resolution_attempt_events_append_only','app.forbid_update_delete()','attempt events are append-only');
select is((select count(*)::int from public.cycle_count_resolution_action_rules where action='item_moved_to_counted_location' and destination_mode='observed'),1,'counted relocation derives its destination');
select is((select count(*)::int from public.cycle_count_resolution_action_rules where action='item_moved_to_reviewed_location' and destination_mode='reviewed'),1,'reviewed relocation is separately named');
select is((select count(*)::int from public.cycle_count_resolution_action_rules where discrepancy_kind='lot_shortage' and action='item_loss_recorded'),0,'nonsensical loss action is forbidden for lots');
select is((select count(*)::int from information_schema.role_table_grants where table_schema='public' and table_name in ('cycle_count_resolution_attempts','inventory_loss_events') and grantee in ('anon','authenticated','PUBLIC')),0,'audit internals have no direct client grant');
select is((select prosecdef from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='execute_cycle_count_resolution_attempt'),true,'execution is SECURITY DEFINER');
select is((select proconfig @> array['search_path=""'] from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='execute_cycle_count_resolution_attempt'),true,'execution pins search path');
select * from finish(); rollback;
