begin;
create extension if not exists pgtap;
select plan(60);

select has_view('public','acquisition_line_overview','overview exists');
select is((select reloptions @> array['security_invoker=true'] from pg_class where oid='public.acquisition_line_overview'::regclass),true,'security invoker');
select has_function('public','list_acquisition_lines',array['uuid','text','text','text','text','text','text','text','text','integer','integer'],'list RPC exists');
select has_function('public','get_acquisition_facets',array['uuid'],'facet RPC exists');
select ok(has_function_privilege('authenticated','public.list_acquisition_lines(uuid,text,text,text,text,text,text,text,text,integer,integer)','EXECUTE'),'authenticated lists');
select ok(has_function_privilege('authenticated','public.get_acquisition_facets(uuid)','EXECUTE'),'authenticated facets');
select ok(not has_function_privilege('anon','public.list_acquisition_lines(uuid,text,text,text,text,text,text,text,text,integer,integer)','EXECUTE'),'anon list denied');
select ok(not has_function_privilege('anon','public.get_acquisition_facets(uuid)','EXECUTE'),'anon facets denied');
select ok(not has_table_privilege('anon','public.acquisition_line_overview','SELECT'),'anon view denied');
select ok(has_table_privilege('authenticated','public.acquisition_line_overview','SELECT'),'authenticated view select');

select has_column('public','acquisition_line_overview','workspace_id','workspace');
select has_column('public','acquisition_line_overview','acquisition_line_item_id','line id');
select has_column('public','acquisition_line_overview','acquisition_line_public_id','line public id');
select has_column('public','acquisition_line_overview','acquisition_import_job_id','acquisition job');
select has_column('public','acquisition_line_overview','source_import_job_id','source job');
select has_column('public','acquisition_line_overview','source_record_id','source record');
select has_column('public','acquisition_line_overview','source_system_id','source system');
select has_column('public','acquisition_line_overview','source_system_public_id','source public id');
select has_column('public','acquisition_line_overview','source_system_kind','source kind');
select has_column('public','acquisition_line_overview','quantity','quantity');
select has_column('public','acquisition_line_overview','description','description');
select has_column('public','acquisition_line_overview','reference_number','reference');
select has_column('public','acquisition_line_overview','source_detail','source detail');
select has_column('public','acquisition_line_overview','created_at','created');
select has_column('public','acquisition_line_overview','business_vertical','vertical');
select has_column('public','acquisition_line_overview','full_title','title');
select has_column('public','acquisition_line_overview','delivered_item_title','delivered item');
select has_column('public','acquisition_line_overview','seller_normalized','seller');
select has_column('public','acquisition_line_overview','acquisition_order_id','order id');
select has_column('public','acquisition_line_overview','acquisition_order_public_id','order public id');
select has_column('public','acquisition_line_overview','source_order_reference','source order');
select has_column('public','acquisition_line_overview','order_status','order status');
select has_column('public','acquisition_line_overview','source_reported_status','source status');
select has_column('public','acquisition_line_overview','occurred_at','occurred');
select has_column('public','acquisition_line_overview','supplier_id','supplier id');
select has_column('public','acquisition_line_overview','supplier_public_id','supplier public id');
select has_column('public','acquisition_line_overview','classification_id','classification id');
select has_column('public','acquisition_line_overview','classification_public_id','classification public id');
select has_column('public','acquisition_line_overview','classification_option_id','option id');
select has_column('public','acquisition_line_overview','classification_key','classification key');
select has_column('public','acquisition_line_overview','classification_label','classification label');
select has_column('public','acquisition_line_overview','classification_method','method');
select has_column('public','acquisition_line_overview','confidence','confidence');
select has_column('public','acquisition_line_overview','rule_id','rule id');
select has_column('public','acquisition_line_overview','rule_public_id','rule public id');
select has_column('public','acquisition_line_overview','rule_logical_key','rule key');
select has_column('public','acquisition_line_overview','rule_version','rule version');
select has_column('public','acquisition_line_overview','classification_created_at','classification created');
select has_column('public','acquisition_line_overview','classification_state','state');
select has_column('public','acquisition_line_overview','search_text','search');

select throws_ok($$select public.list_acquisition_lines(gen_random_uuid())$$,'42501','unauthorized_workspace','foreign workspace denied');
select throws_ok($$select public.get_acquisition_facets(gen_random_uuid())$$,'42501','unauthorized_workspace','foreign facets denied');
select is((select count(*) from public.acquisition_line_overview),(select count(distinct acquisition_line_item_id) from public.acquisition_line_overview),'one row per line');
select is((select count(*) from public.acquisition_line_overview where classification_state not in ('classified','needs_review','unclassified')),0::bigint,'closed states');
select is((select count(*) from public.acquisition_line_overview where classification_id is null and classification_state <> 'unclassified'),0::bigint,'missing is unclassified');
select is((select count(*) from public.acquisition_line_overview where classification_key='unreviewed' and classification_state <> 'needs_review'),0::bigint,'unreviewed needs review');
select is((select count(*) from public.acquisition_line_overview v join public.acquisition_import_jobs j on j.id=v.acquisition_import_job_id where j.status <> 'committed'),0::bigint,'committed only');
select ok(position('source_reported_total_minor' in pg_get_viewdef('public.acquisition_line_overview'::regclass))=0,'no money total');
select ok(position('whatnot' in lower(pg_get_viewdef('public.acquisition_line_overview'::regclass)))=0,'no legacy rows');
select ok(position('limit 1' in lower(pg_get_viewdef('public.acquisition_line_overview'::regclass)))=0,'no arbitrary limit');

select * from finish();
rollback;
