begin;
create extension if not exists pgtap;
select plan(18);
select has_table('public','acquisition_payments','payment table exists');
select has_table('public','acquisition_shipments','shipment table exists');
select has_column('public','acquisition_payments','reversal_reason','payment reversal evidence exists');
select has_column('public','acquisition_shipments','received_at','shipment delivery evidence exists');
select has_function('public','record_acquisition_payment',array['uuid','text','timestamp with time zone','bigint','text','text','text','uuid','text','text'],'record payment exists');
select has_function('public','reverse_acquisition_payment',array['uuid','text','text','text'],'reverse payment exists');
select has_function('public','create_acquisition_shipment',array['uuid','text','text','text','timestamp with time zone','timestamp with time zone','text','bigint','text','uuid','text','text'],'create shipment exists');
select has_function('public','transition_acquisition_shipment',array['uuid','text','text','text','timestamp with time zone','text','text'],'transition shipment exists');
select has_function('public','get_acquisition_line_detail',array['uuid','text'],'detail RPC exists');
select has_function('public','classify_acquisition_line_by_public_id',array['uuid','text'],'classification public ID wrapper exists');
select has_function('public','override_acquisition_line_classification_by_public_id',array['uuid','text','text','text'],'override public ID wrapper exists');
select is((select relrowsecurity from pg_class where oid='public.acquisition_payments'::regclass),true,'payment RLS enabled');
select is((select relrowsecurity from pg_class where oid='public.acquisition_shipments'::regclass),true,'shipment RLS enabled');
select ok(not has_table_privilege('authenticated','public.acquisition_payments','INSERT'),'authenticated cannot insert payments');
select ok(not has_table_privilege('authenticated','public.acquisition_shipments','UPDATE'),'authenticated cannot update shipments');
select ok(has_function_privilege('authenticated','public.get_acquisition_line_detail(uuid,text)','EXECUTE'),'authenticated can read detail');
select throws_ok($$insert into public.acquisition_payments(workspace_id,acquisition_order_id,paid_at,amount_minor,currency,instrument,idempotency_key,payload_fingerprint,created_by) values(gen_random_uuid(),gen_random_uuid(),now(),0,'usd','wire','x','x',gen_random_uuid())$$,null,null,'invalid payments fail closed');
select throws_ok($$insert into public.acquisition_shipments(workspace_id,acquisition_order_id,status,received_at,create_idempotency_key,create_fingerprint,created_by) values(gen_random_uuid(),gen_random_uuid(),'expected',now(),'12345678','x',gen_random_uuid())$$,null,null,'invalid shipment timestamps fail closed');
select * from finish(); rollback;
