begin;
create extension if not exists pgtap;
select plan(30);
select has_table('public','acquisition_payment_reversals','payment reversal ledger exists');
select has_table('public','acquisition_shipment_transitions','shipment transition ledger exists');
select has_column('public','acquisition_payments','reversal_event_id','payment links reversal event');
select has_column('public','acquisition_payment_reversals','public_id','reversal governed identity');
select has_column('public','acquisition_payment_reversals','workspace_id','reversal workspace');
select has_column('public','acquisition_payment_reversals','acquisition_payment_id','reversal payment');
select has_column('public','acquisition_payment_reversals','reason','reversal reason');
select has_column('public','acquisition_payment_reversals','idempotency_key','reversal operation key');
select has_column('public','acquisition_payment_reversals','payload_fingerprint','reversal fingerprint');
select has_column('public','acquisition_payment_reversals','reversed_by','reversal actor');
select has_column('public','acquisition_payment_reversals','reversed_at','reversal time');
select has_column('public','acquisition_shipment_transitions','public_id','transition governed identity');
select has_column('public','acquisition_shipment_transitions','workspace_id','transition workspace');
select has_column('public','acquisition_shipment_transitions','acquisition_shipment_id','transition shipment');
select has_column('public','acquisition_shipment_transitions','from_status','transition from state');
select has_column('public','acquisition_shipment_transitions','to_status','transition to state');
select has_column('public','acquisition_shipment_transitions','applied','transition outcome');
select has_column('public','acquisition_shipment_transitions','received_at','delivery time');
select has_column('public','acquisition_shipment_transitions','reason','transition reason');
select has_column('public','acquisition_shipment_transitions','idempotency_key','transition operation key');
select has_column('public','acquisition_shipment_transitions','payload_fingerprint','transition fingerprint');
select has_column('public','acquisition_shipment_transitions','transitioned_by','transition actor');
select is((select relrowsecurity from pg_class where oid='public.acquisition_payment_reversals'::regclass),true,'reversal RLS enabled');
select is((select relrowsecurity from pg_class where oid='public.acquisition_shipment_transitions'::regclass),true,'transition RLS enabled');
select ok(not has_table_privilege('authenticated','public.acquisition_payment_reversals','INSERT'),'authenticated cannot insert reversals');
select ok(not has_table_privilege('authenticated','public.acquisition_payment_reversals','UPDATE'),'authenticated cannot update reversals');
select ok(not has_table_privilege('authenticated','public.acquisition_payment_reversals','DELETE'),'authenticated cannot delete reversals');
select ok(not has_table_privilege('authenticated','public.acquisition_shipment_transitions','INSERT'),'authenticated cannot insert transitions');
select ok(not has_table_privilege('authenticated','public.acquisition_shipment_transitions','UPDATE'),'authenticated cannot update transitions');
select ok(not has_table_privilege('authenticated','public.acquisition_shipment_transitions','DELETE'),'authenticated cannot delete transitions');
select * from finish(); rollback;
