begin;
create extension if not exists pgtap;
select plan(45);
create temporary table contract_source as select pg_get_functiondef('public.create_acquisition_shipment(uuid,text,text,text,timestamptz,timestamptz,text,bigint,text,uuid,text,text)'::regprocedure) body;
select ok(position('p_status not in (''expected'',''in_transit'')' in (select body from contract_source))>0,'initial states are restricted');
select ok(position('car text:=nullif(btrim(p_carrier)' in (select body from contract_source))>0,'carrier display is trimmed only');
select ok(position('track text:=nullif(btrim(p_tracking_number)' in (select body from contract_source))>0,'tracking display is trimmed only');
select ok(position('normalized_car text' in (select body from contract_source))>0,'carrier natural identity is separate');
select ok(position('normalized_track text' in (select body from contract_source))>0,'tracking natural identity is separate');
select ok(position('recv:=null' in (select body from contract_source))>0,'creation never infers received time');
select ok(position('carrier,tracking_number' in (select body from contract_source))>0,'display evidence is inserted');
select ok(position('values(p_workspace_id,o.id,car,track' in (select body from contract_source))>0,'raw trimmed forms are persisted');
select ok(position('lower(btrim(s.carrier))=normalized_car' in (select body from contract_source))>0,'carrier duplicate comparison normalized');
select ok(position('regexp_replace(btrim(s.tracking_number)' in (select body from contract_source))>0,'tracking duplicate comparison normalized');
select ok(position('invalid_initial_status' in (select body from contract_source))>0,'bounded initial status error');
select ok(position('invalid_shipping_reference_amount' in (select body from contract_source))>0,'bounded reference amount error');
select ok(position('invalid_source_evidence' in (select body from contract_source))>0,'bounded source evidence error');
select ok(position('idempotency_conflict' in (select body from contract_source))>0,'bounded idempotency error');
select ok(position('duplicate_tracking' in (select body from contract_source))>0,'bounded duplicate tracking error');
select ok(position('pg_advisory_xact_lock' in (select body from contract_source))>0,'create key is serialized');
select ok(position('create_idempotency_key=key' in (select body from contract_source))>0,'create replay loads by key');
select ok(position('create_fingerprint<>fp' in (select body from contract_source))>0,'replay verifies fingerprint');
select ok(position('shipping_cost_minor' in (select body from contract_source))>0,'reference amount participates in fingerprint');
select ok(position('source_record_id' in (select body from contract_source))>0,'source evidence participates in fingerprint');
select ok(position('evidence_note' in (select body from contract_source))>0,'evidence note participates in fingerprint');
select ok(position('app.log_audit_event' in (select body from contract_source))>0,'shipment creation audits');
select ok(position('array[''owner'',''operator'']' in (select body from contract_source))>0,'owner and operator capability enforced');
select ok(position('j.status=''committed''' in (select body from contract_source))>0,'committed order enforced');
select ok(position('char_length(key) not between 8 and 200' in (select body from contract_source))>0,'key bounds enforced');
select ok(position('char_length(coalesce(car,''''))>100' in (select body from contract_source))>0,'carrier bounds enforced');
select ok(position('char_length(coalesce(track,''''))>200' in (select body from contract_source))>0,'tracking bounds enforced');
select ok(position('char_length(coalesce(note,''''))>1000' in (select body from contract_source))>0,'evidence bounds enforced');
select ok(position('cur !~ ''^[A-Z]{3}$''' in (select body from contract_source))>0,'currency syntax enforced');
select ok(position('p_expected_at<p_shipped_at' in (select body from contract_source))>0,'date order enforced');
select ok(position('perform pg_advisory_xact_lock' in (select body from contract_source))>0,'advisory lock occurs before replay');
select ok(position('replayed'',true' in (select body from contract_source))>0,'canonical replay receipt');
select ok(position('replayed'',false' in (select body from contract_source))>0,'new create receipt');
select ok(position('lower(regexp_replace' in (select body from contract_source))>0,'format-insensitive tracking identity');
select ok(position('upper(btrim(p_currency))' in (select body from contract_source))>0,'currency normalizes uppercase');
select ok(position('p_shipping_cost_minor is null)<>(cur is null' in (select body from contract_source))>0,'amount currency pair enforced');
select ok(position('acquisition_not_found' in (select body from contract_source))>0,'missing committed order bounded');
select ok(position('exception when unique_violation' in (select body from contract_source))>0,'unique races translated');
select ok(position('acquisition_shipments' in (select body from contract_source))>0,'governed shipment table targeted');
select ok(position('create_fingerprint' in (select body from contract_source))>0,'durable creation fingerprint stored');
select ok(position('created_by' in (select body from contract_source))>0,'actor stored');
select ok(position('p_shipped_at' in (select body from contract_source))>0,'shipped evidence preserved');
select ok(position('p_expected_at' in (select body from contract_source))>0,'expected evidence preserved');
select ok(position('p_status::public.acquisition_shipment_status' in (select body from contract_source))>0,'closed database status used');
select ok(position('return jsonb_build_object(''shipmentPublicId''' in (select body from contract_source))>0,'public identity returned');
select * from finish();
rollback;
