begin;
create extension if not exists pgtap;
select plan(45);
create temporary table contract_source as select string_agg(pg_get_functiondef(p.oid), E'\n') body from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('get_acquisition_line_detail_by_source','get_acquisition_line_detail','classify_acquisition_line_by_source','classify_acquisition_line_by_public_id','override_acquisition_line_classification_by_source','override_acquisition_line_classification_by_public_id','reverse_acquisition_payment','transition_acquisition_shipment');
select ok(position('source_system_public_id=p_source_system_public_id' in (select body from contract_source))>0,'source identity participates in lookup');
select ok(position('count(distinct acquisition_line_item_id)' in (select body from contract_source))>0,'qualified lookup counts targets');
select ok(position('match_count=0 then return null' in (select body from contract_source))>0,'qualified zero match is bounded not found');
select ok(position('match_count>1 then raise exception ''acquisition_integrity_error''' in (select body from contract_source))>0,'qualified duplicates fail closed');
select ok(position('select count(*) into placement_count' in (select body from contract_source))>0,'active placement cardinality counted');
select ok(position('state=''active''' in (select body from contract_source))>0,'only active placements counted');
select ok(position('placement_count>1 then raise exception ''acquisition_integrity_error''' in (select body from contract_source))>0,'multiple active placements fail closed');
select ok(position('missing_active_placement' in (select body from contract_source))>0,'zero placement state remains explicit');
select ok(position('''identity'',jsonb_build_object' in (select body from contract_source))>0,'response carries identity object');
select ok(position('''sourceSystemPublicId'',v.source_system_public_id' in (select body from contract_source))>0,'response carries exact source id');
select ok(position('''linePublicId'',v.acquisition_line_public_id' in (select body from contract_source))>0,'response carries exact line id');
select ok(position('''reversalEvent''' in (select body from contract_source))>0,'response carries reversal event');
select ok(position('''transitionHistory''' in (select body from contract_source))>0,'response carries transition history');
select ok(position('''allowedNextTransitions''' in (select body from contract_source))>0,'response carries allowed transitions');
select ok(position('''actorId'',pr.reversed_by' in (select body from contract_source))>0,'reversal actor carried');
select ok(position('''reason'',pr.reason' in (select body from contract_source))>0,'reversal reason carried');
select ok(position('''actorId'',t.transitioned_by' in (select body from contract_source))>0,'transition actor carried');
select ok(position('''applied'',t.applied' in (select body from contract_source))>0,'transition application state carried');
select ok(position('sourceRecordPublicIdentity' in (select body from contract_source))>0,'governed source record identity carried');
select ok(position('acquisitionImportPublicIdentity' in (select body from contract_source))>0,'governed import identity carried');
select ok(position('classificationHistory' in (select body from contract_source))>0,'classification history carried');
select ok(position('paymentSummary' in (select body from contract_source))>0,'payment summary carried');
select ok(position('sourceReportedTotalMinor' in (select body from contract_source))>0,'source total remains separate');
select ok(position('shippingReferenceMinor' in (select body from contract_source))>0,'shipping reference remains separate');
select ok(position('historicalLegacyImported' in (select body from contract_source))>0,'coverage limitation explicit');
select ok(position('governed_native_committed' in (select body from contract_source))>0,'coverage contract explicit');
select ok(position('public.classify_acquisition_line(line_id)' in (select body from contract_source))>0,'qualified classifier reuses core algorithm');
select ok(position('public.override_acquisition_line_classification(line_id' in (select body from contract_source))>0,'qualified override reuses core algorithm');
select ok(position('ambiguous_acquisition_line_id' in (select body from contract_source))>0,'legacy detail ambiguity bounded');
select ok(position('count(distinct acquisition_line_item_id),min(source_system_public_id)' in (select body from contract_source))>0,'legacy wrapper counts matches');
select ok(position('return public.get_acquisition_line_detail_by_source' in (select body from contract_source))>0,'legacy unique target delegates safely');
select ok(position('return public.classify_acquisition_line_by_source' in (select body from contract_source))>0,'legacy classifier delegates safely');
select ok(position('return public.override_acquisition_line_classification_by_source' in (select body from contract_source))>0,'legacy override delegates safely');
select ok(position('array[''owner'',''operator'',''viewer'']' in (select body from contract_source))>0,'detail capability includes viewer');
select ok(position('array[''owner'',''operator'']' in (select body from contract_source))>0,'classifier capability excludes viewer');
select ok(position('array[''owner'']' in (select body from contract_source))>0,'override capability owner only');
select ok(position('acquisition_not_found' in (select body from contract_source))>0,'classification zero match bounded');
select ok(position('acquisition_integrity_error' in (select body from contract_source))>0,'qualified integrity error bounded');
select ok(position('get_acquisition_line_detail_by_source' in (select body from contract_source))>0,'public execution revoked');
select ok(position('get_acquisition_line_detail_by_source' in (select body from contract_source))>0,'authenticated execution granted');
select ok(position('classificationOptions' in (select body from contract_source))>0,'detail supplies governed options');
select ok(position('ownerOverrideReason' in (select body from contract_source))>0,'classification reason history carried');
select ok(position('reversalPublicId' in (select body from contract_source))>0,'durable reversal receipts exist');
select ok(position('transitionPublicId' in (select body from contract_source))>0,'durable transition receipts exist');
select ok(position('receivedAt' in (select body from contract_source))>0,'explicit delivery evidence exposed');
select * from finish();
rollback;
