begin;
create extension if not exists pgtap;
select plan(15);
select has_table('public','acquisition_line_exclusions','exclusion decision table exists');
select has_column('public','acquisition_line_exclusions','public_id','governed public identity exists');
select has_column('public','acquisition_line_exclusions','decision_state','decision state exists');
select has_column('public','acquisition_line_exclusions','reason','reason exists');
select has_column('public','acquisition_line_exclusions','idempotency_key','durable operation key exists');
select col_not_null('public','acquisition_line_exclusions','workspace_id','workspace is required');
select col_not_null('public','acquisition_line_exclusions','reason','reason is required');
select has_function('public','exclude_acquisition_line_by_source',array['uuid','text','text','text','text'],'source-qualified exclude exists');
select has_function('public','restore_acquisition_line_by_source',array['uuid','text','text','text','text'],'source-qualified restore exists');
select has_function('app','assert_acquisition_line_eligible_for_downstream',array['uuid','uuid'],'downstream guard exists');
select ok((select relrowsecurity from pg_class where oid='public.acquisition_line_exclusions'::regclass),'RLS enabled');
select ok(has_table_privilege('authenticated','public.acquisition_line_exclusions','select'),'members can read decisions');
select ok(not has_table_privilege('authenticated','public.acquisition_line_exclusions','insert'),'authenticated cannot directly insert');
select ok(not has_table_privilege('authenticated','public.acquisition_line_exclusions','delete'),'authenticated cannot directly delete');
select is((select count(*)::int from public.schema_migrations_log where migration_name='20260806000700_acquisition_line_exclusions'),1,'migration ledger recorded once');
select * from finish();
rollback;
