export type Role='owner'|'operator'|'viewer';
export interface Payment {publicId:string;paidAt:string;amountMinor:number;currency:string;instrument:string;externalReference:string|null;evidenceNote:string|null;state:'active'|'reversed';reversedAt:string|null;reversalReason:string|null}
export interface Shipment {publicId:string;carrier:string|null;trackingNumber:string|null;status:string;shippedAt:string|null;expectedAt:string|null;receivedAt:string|null;shippingReferenceMinor:number|null;currency:string|null;evidenceNote:string|null;allowedNextTransitions:string[]}
export interface AcquisitionDetail {coverage:'governed_native_committed';historicalLegacyImported:false;line:{publicId:string;quantity:number;description:string|null;referenceNumber:string|null;createdAt:string;businessVertical:string|null;fullTitle:string|null;deliveredItemTitle:string|null;sellerNormalized:string|null};order:{publicId:string;sourceOrderReference:string;status:string;sourceReportedStatus:string|null;sourceReportedTotalMinor:number|null;currency:string|null;occurredAt:string|null;channel:{publicId:string;name:string};supplier:{publicId:string;displayName:string};sourceSystem:{publicId:string;kind:string}};placement:{lotPublicId:string|null;sequence:number|null;label:string|null;integrityState:string};classification:null|{publicId:string;optionKey:string;optionLabel:string;method:string;confidence:number;createdAt:string;state:string};classificationHistory:Array<{publicId:string;optionKey:string;optionLabel:string;method:string;confidence:number;createdAt:string;supersededAt:string|null;ownerOverrideReason:string|null}>;classificationOptions:Array<{key:string;label:string}>;payments:Payment[];paymentSummary:{activeCount:number;activeCurrencies:string[];mixedCurrencies:boolean;activeTotalMinor:number|null;sourceReportedTotalMinor:number|null;differenceMinor:number|null};shipments:Shipment[];sourceEvidence:Record<string,unknown>}
export class AcquisitionDetailError extends Error{readonly code:string;readonly status:number;constructor(code:string,status:number){super(code);this.code=code;this.status=status}}
async function call<T>(tokens:()=>Promise<string|null>,path:string,workspaceId:string,init?:RequestInit):Promise<T>{const token=await tokens();if(!token)throw new AcquisitionDetailError('signed_out',401);const q=path.includes('?')?'&':'?';const response=await fetch(`/api/acquisition${path}${q}workspaceId=${encodeURIComponent(workspaceId)}`,{...init,headers:{authorization:`Bearer ${token}`,'content-type':'application/json',...init?.headers}});const body=await response.json().catch(()=>null) as {error?:string}|null;if(!response.ok)throw new AcquisitionDetailError(body?.error??'dependency_failed',response.status);return body as T}
export const acquisitionDetailKey=(workspaceId:string,lineId:string)=>['acquisition-detail',workspaceId,lineId] as const;
export function parseMinorUnits(value:string):number|null {const m=value.trim().match(/^(\d+)(?:\.(\d{1,2}))?$/);if(!m)return null;const n=Number(m[1])*100+Number((m[2]??'').padEnd(2,'0'));return Number.isSafeInteger(n)?n:null}
export function createAcquisitionDetailTransport(tokens:()=>Promise<string|null>){const post=<T>(path:string,w:string,body:unknown)=>call<T>(tokens,path,w,{method:'POST',body:JSON.stringify(body)});return{detail:(w:string,id:string)=>call<AcquisitionDetail>(tokens,`/lines/${encodeURIComponent(id)}`,w),classify:(w:string,id:string)=>post(`/lines/${encodeURIComponent(id)}/classify`,w,{}),override:(w:string,id:string,classificationOptionKey:string,reason:string)=>post(`/lines/${encodeURIComponent(id)}/classification-override`,w,{classificationOptionKey,reason}),recordPayment:(w:string,order:string,body:unknown)=>post(`/orders/${encodeURIComponent(order)}/payments`,w,body),reversePayment:(w:string,id:string,reason:string,idempotencyKey:string)=>post(`/payments/${encodeURIComponent(id)}/reverse`,w,{reason,idempotencyKey}),createShipment:(w:string,order:string,body:unknown)=>post(`/orders/${encodeURIComponent(order)}/shipments`,w,body),transitionShipment:(w:string,id:string,body:unknown)=>post(`/shipments/${encodeURIComponent(id)}/transition`,w,body)}}
