import {afterEach,describe,expect,it,vi} from 'vitest';
import {AcquisitionDetailError,acquisitionDetailKey,createAcquisitionDetailTransport,parseMinorUnits,validLocalDate} from './acquisitionDetailApi';
afterEach(()=>vi.unstubAllGlobals());
const ok=()=>{const fetch=vi.fn().mockResolvedValue({ok:true,json:async()=>({ok:true})});vi.stubGlobal('fetch',fetch);return fetch};
const api=()=>createAcquisitionDetailTransport(async()=> 'caller-token');
describe('source-qualified acquisition detail transport',()=>{
 it('uses canonical source-qualified detail route',async()=>{const f=ok();await api().detail('ws','SRC','LINE');expect(f.mock.calls[0][0]).toBe('/api/acquisition/sources/SRC/lines/LINE?workspaceId=ws')});
 it('encodes source identity',async()=>{const f=ok();await api().detail('ws','source/a','line');expect(f.mock.calls[0][0]).toContain('/sources/source%2Fa/')});
 it('encodes line identity',async()=>{const f=ok();await api().detail('ws','source','line/a');expect(f.mock.calls[0][0]).toContain('/lines/line%2Fa')});
 it('encodes workspace identity',async()=>{const f=ok();await api().detail('workspace/a','source','line');expect(f.mock.calls[0][0]).toContain('workspaceId=workspace%2Fa')});
 it('forwards caller bearer token',async()=>{const f=ok();await api().detail('ws','s','l');expect(f.mock.calls[0][1].headers.authorization).toBe('Bearer caller-token')});
 it('uses source-qualified classify route',async()=>{const f=ok();await api().classify('ws','s','l');expect(f.mock.calls[0][0]).toContain('/sources/s/lines/l/classify')});
 it('uses source-qualified override route',async()=>{const f=ok();await api().override('ws','s','l','sealed','evidence');expect(f.mock.calls[0][0]).toContain('/sources/s/lines/l/classification-override')});
 it('forwards override evidence',async()=>{const f=ok();await api().override('ws','s','l','sealed','evidence');expect(JSON.parse(f.mock.calls[0][1].body)).toEqual({classificationOptionKey:'sealed',reason:'evidence'})});
 it('forwards payment idempotency key unchanged',async()=>{const f=ok();await api().recordPayment('ws','order',{idempotencyKey:'pay-key-123'});expect(f.mock.calls[0][1].body).toContain('pay-key-123')});
 it('forwards reversal idempotency key unchanged',async()=>{const f=ok();await api().reversePayment('ws','payment','reason','reverse-key-123');expect(JSON.parse(f.mock.calls[0][1].body).idempotencyKey).toBe('reverse-key-123')});
 it('forwards shipment display evidence unchanged',async()=>{const f=ok();await api().createShipment('ws','order',{carrier:'USPS Priority Mail',trackingNumber:'9400 1234-5678'});expect(f.mock.calls[0][1].body).toContain('USPS Priority Mail');expect(f.mock.calls[0][1].body).toContain('9400 1234-5678')});
 it('forwards transition received time',async()=>{const f=ok();await api().transitionShipment('ws','ship',{receivedAt:'2026-08-06T12:00:00.000Z',idempotencyKey:'transition-key'});expect(f.mock.calls[0][1].body).toContain('2026-08-06T12:00:00.000Z')});
 it('uses POST for mutations',async()=>{const f=ok();await api().classify('ws','s','l');expect(f.mock.calls[0][1].method).toBe('POST')});
 it('does not use legacy line route',async()=>{const f=ok();await api().detail('ws','s','l');expect(f.mock.calls[0][0]).not.toMatch(/acquisition\/lines\/l/) });
 it('fails closed while signed out',async()=>{await expect(createAcquisitionDetailTransport(async()=>null).detail('ws','s','l')).rejects.toEqual(expect.objectContaining({code:'signed_out'}))});
 it('preserves bounded server errors',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:false,status:409,json:async()=>({error:'stale_status'})}));await expect(api().detail('ws','s','l')).rejects.toEqual(expect.objectContaining<Partial<AcquisitionDetailError>>({code:'stale_status',status:409}))});
 it('bounds malformed error responses',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:false,status:502,json:async()=>null}));await expect(api().detail('ws','s','l')).rejects.toEqual(expect.objectContaining({code:'dependency_failed'}))});
 it('keys detail by workspace and both identities',()=>expect(acquisitionDetailKey('w','s','l')).toEqual(['acquisition-detail','w','s','l']));
 it('parses exact whole minor units',()=>expect(parseMinorUnits('12')).toBe(1200));
 it('parses exact fractional minor units',()=>expect(parseMinorUnits('12.34')).toBe(1234));
 it('pads one fractional digit',()=>expect(parseMinorUnits('12.3')).toBe(1230));
 it('rejects more than two fractional digits',()=>expect(parseMinorUnits('12.345')).toBeNull());
 it('rejects unsafe integer amounts',()=>expect(parseMinorUnits('999999999999999999999')).toBeNull());
 it('validates local dates without throwing',()=>expect(validLocalDate('not-a-date')).toBeNull());
 it('normalizes valid local dates',()=>expect(validLocalDate('2026-08-06T12:00')).toMatch(/^2026-08-06T12:00:00\.000Z$/));
});
