export type Role='owner'|'operator'|'viewer';
export type ShipmentStatus='expected'|'in_transit'|'delivered'|'lost'|'cancelled';
export type PaymentInstrument='card'|'bank'|'balance'|'credit'|'cash'|'other';
export interface PaymentReversalEvent {publicId:string;actorId:string;reversedAt:string;reason:string}
export interface ShipmentTransition {publicId:string;fromStatus:ShipmentStatus;toStatus:ShipmentStatus;applied:boolean;receivedAt:string|null;reason:string|null;actorId:string;createdAt:string}
export interface Payment {publicId:string;paidAt:string;amountMinor:number;currency:string;instrument:PaymentInstrument;externalReference:string|null;evidenceNote:string|null;state:'active'|'reversed';reversedAt:string|null;reversalReason:string|null;reversalEvent:PaymentReversalEvent|null}
export interface Shipment {publicId:string;carrier:string|null;trackingNumber:string|null;status:ShipmentStatus;shippedAt:string|null;expectedAt:string|null;receivedAt:string|null;shippingReferenceMinor:number|null;currency:string|null;evidenceNote:string|null;transitionHistory:ShipmentTransition[];allowedNextTransitions:ShipmentStatus[]}
export interface AcquisitionDetail {coverage:'governed_native_committed';historicalLegacyImported:false;identity:{sourceSystemPublicId:string;linePublicId:string};line:{publicId:string;quantity:number;description:string|null;referenceNumber:string|null;createdAt:string;businessVertical:string|null;fullTitle:string|null;deliveredItemTitle:string|null;sellerNormalized:string|null};order:{publicId:string;sourceOrderReference:string;status:string;sourceReportedStatus:string|null;sourceReportedTotalMinor:number|null;currency:string|null;occurredAt:string|null;channel:{publicId:string;name:string};supplier:{publicId:string;displayName:string};sourceSystem:{publicId:string;kind:string}};placement:{lotPublicId:string|null;sequence:number|null;label:string|null;integrityState:'current'|'missing_active_placement'};classification:null|{publicId:string;optionKey:string;optionLabel:string;method:string;confidence:number;createdAt:string;state:string};classificationHistory:Array<{publicId:string;optionKey:string;optionLabel:string;method:string;confidence:number;createdAt:string;supersededAt:string|null;ownerOverrideReason:string|null}>;classificationOptions:Array<{key:string;label:string}>;payments:Payment[];paymentSummary:{activeCount:number;activeCurrencies:string[];mixedCurrencies:boolean;activeTotalMinor:number|null;sourceReportedTotalMinor:number|null;differenceMinor:number|null};shipments:Shipment[];sourceEvidence:{sourceSystemPublicId:string;
 /** public.source_records.source_row_key — a raw source row key, never an RV-style governed public identity. */
 sourceRecordRowKey:string|null;
 /** public.import_jobs.public_id — the SOURCE import job. acquisition_import_jobs has no governed public ID. */
 sourceImportJobPublicId:string|null}}
export class AcquisitionDetailError extends Error{readonly code:string;readonly status:number;constructor(code:string,status:number){super(code);this.code=code;this.status=status}}
async function call<T>(tokens:()=>Promise<string|null>,path:string,workspaceId:string,init?:RequestInit):Promise<T>{const token=await tokens();if(!token)throw new AcquisitionDetailError('signed_out',401);const q=path.includes('?')?'&':'?';const response=await fetch(`/api/acquisition${path}${q}workspaceId=${encodeURIComponent(workspaceId)}`,{...init,headers:{authorization:`Bearer ${token}`,'content-type':'application/json',...init?.headers}});const body=await response.json().catch(()=>null) as {error?:string}|null;if(!response.ok)throw new AcquisitionDetailError(body?.error??'dependency_failed',response.status);return body as T}
export const acquisitionDetailKey=(workspaceId:string,sourceId:string,lineId:string)=>['acquisition-detail',workspaceId,sourceId,lineId] as const;
export function parseMinorUnits(value:string):number|null {const m=value.trim().match(/^(\d+)(?:\.(\d{1,2}))?$/);if(!m)return null;const whole=BigInt(m[1]),fraction=BigInt((m[2]??'').padEnd(2,'0'));const n=whole*100n+fraction;return n<=BigInt(Number.MAX_SAFE_INTEGER)?Number(n):null}
export function validLocalDate(value:string):string|null {if(!value)return null;const parsed=new Date(value);return Number.isFinite(parsed.getTime())?parsed.toISOString():null}
export function createAcquisitionDetailTransport(tokens:()=>Promise<string|null>){const post=<T>(path:string,w:string,body:unknown)=>call<T>(tokens,path,w,{method:'POST',body:JSON.stringify(body)});const line=(source:string,id:string)=>`/sources/${encodeURIComponent(source)}/lines/${encodeURIComponent(id)}`;return{detail:(w:string,source:string,id:string)=>call<AcquisitionDetail>(tokens,line(source,id),w),classify:(w:string,source:string,id:string)=>post(line(source,id)+'/classify',w,{}),override:(w:string,source:string,id:string,classificationOptionKey:string,reason:string)=>post(line(source,id)+'/classification-override',w,{classificationOptionKey,reason}),recordPayment:(w:string,order:string,body:unknown)=>post(`/orders/${encodeURIComponent(order)}/payments`,w,body),reversePayment:(w:string,id:string,reason:string,idempotencyKey:string)=>post(`/payments/${encodeURIComponent(id)}/reverse`,w,{reason,idempotencyKey}),createShipment:(w:string,order:string,body:unknown)=>post(`/orders/${encodeURIComponent(order)}/shipments`,w,body),transitionShipment:(w:string,id:string,body:unknown)=>post(`/shipments/${encodeURIComponent(id)}/transition`,w,body)}}
