import {describe,expect,it} from 'vitest';import {createCycleCountTransport} from './cycleCountApi';
function client(){const calls:Array<{fn:string;args:Record<string,unknown>}>=[];const c={from:()=>{const q:any={select:()=>q,eq:()=>q,order:async()=>({data:[],error:null})};return q},rpc:async(fn:string,args:Record<string,unknown>)=>{calls.push({fn,args});return {data:{outcome:'accepted'},error:null}}};return {c,calls}}
describe('cycle count transport',()=>{
 it('requires an active workspace',async()=>{const {c}=client();await expect(createCycleCountTransport(c as never,()=>null).progress('s')).rejects.toThrow('No workspace selected')});
 it('passes explicit round mutations with client keys',async()=>{const {c,calls}=client();const api=createCycleCountTransport(c as never,()=> 'ws');await api.observeItem('s','scan','BIN-A','key');await api.observeLot('s','lot',8,'key2');expect(calls).toEqual([{fn:'observe_cycle_count_item',args:{p_workspace_id:'ws',p_session_id:'s',p_identifier:'scan',p_observed_location_code:'BIN-A',p_idempotency_key:'key',p_note:null}},{fn:'observe_cycle_count_lot',args:{p_workspace_id:'ws',p_session_id:'s',p_lot_public_id:'lot',p_observed_quantity:8,p_idempotency_key:'key2',p_note:null}}])});
 it('keeps recount selection separate from start',async()=>{const {c,calls}=client();const api=createCycleCountTransport(c as never,()=> 'ws');await api.selectRecount('s',['d1','d2'],'verify');await api.beginRecount('s','verify');expect(calls.map(x=>x.fn)).toEqual(['mark_cycle_count_discrepancies_for_recount','begin_cycle_count_recount'])});
 it('uses governed review reads and two-stage resolution',async()=>{const {c,calls}=client();const api=createCycleCountTransport(c as never,()=> 'ws');await api.discrepancies('s');await api.history('s');await api.attempts('s');const created=await api.createAttempt('d','deferred','investigate',null,'k');await api.executeAttempt(String(created.attempt_id??'a'));expect(calls.map(x=>x.fn)).toEqual(['list_current_cycle_count_discrepancies','list_cycle_count_history','list_cycle_count_resolution_attempts','create_cycle_count_resolution_attempt','execute_cycle_count_resolution_attempt'])});
 it('completes through the latest-result authority',async()=>{const {c,calls}=client();const api=createCycleCountTransport(c as never,()=> 'ws');await api.complete('s',false,'reviewed');expect(calls).toEqual([{fn:'complete_cycle_count_latest',args:{p_workspace_id:'ws',p_session_id:'s',p_allow_deferred:false,p_note:'reviewed'}}])});
});
