import { useEffect, useMemo, useRef, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useSearchParams } from 'react-router-dom';
import { AlertTriangle, RefreshCw } from 'lucide-react';
import { createAcquisitionLinesTransport, type AcquisitionOrder, type AcquisitionSort } from '../lib/acquisitionLinesApi';
import { useWorkspace } from '../lib/workspaceContext';
import { createShadowClient } from '../lib/supabaseShadow';
import { tokenProviderFromClient } from '../lib/tokenProvider';

const sorts=new Set<AcquisitionSort>(['occurred_at','created_at','seller','title','quantity','classification']);
const orders=new Set<AcquisitionOrder>(['asc','desc']); const states=new Set(['classified','needs_review','unclassified']);
const PAGE_SIZE=50;
export default function Acquisitions(){
 const {workspace}=useWorkspace(); const [url,setUrl]=useSearchParams(); const [invalid,setInvalid]=useState(false);
 const api=useMemo(()=>createAcquisitionLinesTransport(tokenProviderFromClient(createShadowClient(import.meta.env as unknown as Record<string,string|undefined>))),[]);
 const rawSort=url.get('sort')??'occurred_at',rawOrder=url.get('order')??'desc',rawState=url.get('classificationState');
 const sort=(sorts.has(rawSort as AcquisitionSort)?rawSort:'occurred_at') as AcquisitionSort;
 const order=(orders.has(rawOrder as AcquisitionOrder)?rawOrder:'desc') as AcquisitionOrder;
 const page=Math.max(1,Number(url.get('page'))||1);
 useEffect(()=>{const bad=rawSort!==sort||rawOrder!==order||(rawState!==null&&!states.has(rawState))||String(page)!==(url.get('page')??'1');if(bad){setInvalid(true);const n=new URLSearchParams(url);if(rawSort!==sort)n.delete('sort');if(rawOrder!==order)n.delete('order');if(rawState&&!states.has(rawState))n.delete('classificationState');if(String(page)!==(url.get('page')??'1'))n.delete('page');setUrl(n,{replace:true})}},[rawSort,rawOrder,rawState,sort,order,page,url,setUrl]);
 const previousWorkspace=useRef(workspace?.id);
 useEffect(()=>{if(previousWorkspace.current&&previousWorkspace.current!==workspace?.id){setUrl(new URLSearchParams(),{replace:true});}previousWorkspace.current=workspace?.id},[workspace?.id,setUrl]);
 const params={query:url.get('query')||undefined,classification:url.get('classification')||undefined,seller:url.get('seller')||undefined,businessVertical:url.get('businessVertical')||undefined,method:url.get('method')||undefined,classificationState:rawState&&states.has(rawState)?rawState:undefined,sort,order,limit:PAGE_SIZE,offset:(page-1)*PAGE_SIZE};
 const enabled=Boolean(workspace); const lines=useQuery({queryKey:['acquisition-lines',workspace?.id,params],queryFn:()=>api.lines(workspace!.id,params),enabled,placeholderData:undefined});
 const facets=useQuery({queryKey:['acquisition-facets',workspace?.id],queryFn:()=>api.facets(workspace!.id),enabled,placeholderData:undefined});
 const change=(key:string,value:string)=>{const n=new URLSearchParams(url);if(value){n.set(key,value)}else{n.delete(key)}if(key!=='page')n.delete('page');setUrl(n)};
 return <div className="space-y-5 p-4 md:p-6">
  <header><h1 className="text-2xl font-semibold">Acquisitions</h1><p className="text-sm text-ink-muted">{lines.isLoading?'Loading exact line count…':lines.data?`${lines.data.total.toLocaleString()} filtered lines`:'Exact line count unavailable'}</p></header>
  <div role="note" className="flex gap-3 rounded-xl border border-amber-400/50 bg-amber-400/10 p-4 text-sm"><AlertTriangle className="h-5 w-5 shrink-0 text-amber-600"/><p><strong>Governed-native coverage.</strong> This page contains committed governed-native acquisition lines. Historical legacy Whatnot purchases have not yet been imported; do not add legacy and governed counts together. Historical import occurs in a later reconciliation slice.</p></div>
  {invalid&&<div role="alert" className="rounded border border-amber-400 p-3 text-sm">Unsupported URL filters were removed.</div>}
  <section aria-label="Classification summary" className="flex flex-wrap gap-2">{facets.data?.facets.classificationOptions.map(x=><span key={x.key} className={`rounded-full border px-3 py-1 text-xs ${x.key==='unreviewed'?'border-amber-400 bg-amber-400/10':''}`}>{x.label}: {x.count}{x.key==='unreviewed'?' · review work':''}</span>)}{facets.data&&<span className="rounded-full border px-3 py-1 text-xs">Unclassified: {facets.data.facets.unclassified}</span>}</section>
  <form onSubmit={e=>{e.preventDefault();change('query',String(new FormData(e.currentTarget).get('query')??''))}} className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5"><input name="query" defaultValue={params.query} placeholder="Search acquisitions" className="rounded border border-hairline bg-surface-1 px-3 py-2"/><select value={params.classification??''} onChange={e=>change('classification',e.target.value)} className="rounded border border-hairline bg-surface-1 px-2"><option value="">All classifications</option><option value="unclassified">Unclassified</option>{facets.data?.facets.classificationOptions.map(x=><option key={x.key} value={x.key}>{x.label}</option>)}</select><select value={params.seller??''} onChange={e=>change('seller',e.target.value)} className="rounded border border-hairline bg-surface-1 px-2"><option value="">All sellers</option>{facets.data?.facets.sellers.map(x=><option key={x.value}>{x.value}</option>)}</select><select value={params.businessVertical??''} onChange={e=>change('businessVertical',e.target.value)} className="rounded border border-hairline bg-surface-1 px-2"><option value="">All verticals</option>{facets.data?.facets.businessVerticals.map(x=><option key={x.value}>{x.value}</option>)}</select><select value={params.classificationState??''} onChange={e=>change('classificationState',e.target.value)} className="rounded border border-hairline bg-surface-1 px-2"><option value="">All review states</option><option value="classified">Classified</option><option value="needs_review">Needs review</option><option value="unclassified">Unclassified</option></select><button className="rounded bg-accent px-3 py-2 text-white">Search</button></form>
  {(lines.isLoading||facets.isLoading)&&<p role="status">Loading acquisitions…</p>}
  {(lines.isError||facets.isError)&&<div role="alert" className="rounded border border-red-400 p-4"><p>Acquisition data could not be loaded. No empty result has been assumed.</p><button onClick={()=>{void lines.refetch();void facets.refetch()}} className="mt-2 flex items-center gap-1"><RefreshCw className="h-4 w-4"/>Retry</button></div>}
  {lines.data&&lines.data.rows.length===0&&<p>No acquisitions match these filters.</p>}
  {lines.data&&lines.data.rows.length>0&&<><div className="hidden overflow-x-auto lg:block"><table className="w-full text-sm"><thead><tr className="text-left"><th>Classification</th><th>Date</th><th>Seller</th><th>Product / title</th><th>Qty</th><th>Vertical</th><th>Line / order</th><th>Method</th></tr></thead><tbody>{lines.data.rows.map(r=><tr key={r.acquisition_line_public_id} className="border-t border-hairline"><td>{r.classification_label??'Unclassified'}</td><td>{new Date(r.occurred_at??r.created_at).toLocaleDateString()}</td><td>{r.seller_normalized??'Unknown'}</td><td>{r.full_title??r.delivered_item_title??'Untitled'}</td><td>{r.quantity}</td><td>{r.business_vertical??'Unknown'}</td><td>{r.acquisition_line_public_id}<br/>{r.source_order_reference??'No source order'}</td><td>{r.classification_method??'—'}</td></tr>)}</tbody></table></div><div className="grid gap-3 lg:hidden">{lines.data.rows.map(r=><article key={r.acquisition_line_public_id} className="rounded-xl border border-hairline bg-surface-1 p-4"><div className="flex justify-between"><strong>{r.classification_label??'Unclassified'}</strong><span>Qty {r.quantity}</span></div><h2 className="mt-2 font-medium">{r.full_title??r.delivered_item_title??'Untitled'}</h2><p className="text-sm text-ink-secondary">{r.seller_normalized??'Unknown seller'} · {r.business_vertical??'Unknown vertical'}</p><p className="mt-2 text-xs text-ink-muted">{r.acquisition_line_public_id} · {r.source_order_reference??'No source order'} · {r.classification_method??'No classification method'}</p></article>)}</div></>}
  {lines.data&&<nav className="flex justify-between"><button disabled={page===1} onClick={()=>change('page',String(page-1))}>Previous</button><span>Page {page}</span><button disabled={page*PAGE_SIZE>=lines.data.total} onClick={()=>change('page',String(page+1))}>Next</button></nav>}
 </div>
}
