// @vitest-environment jsdom
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import CycleCounts from './CycleCounts';

const api={list:vi.fn(),progress:vi.fn(),history:vi.fn(),discrepancies:vi.fn(),attempts:vi.fn(),
 observeItem:vi.fn(),observeLot:vi.fn(),observations:vi.fn(),voidObservation:vi.fn(),attestItemAbsence:vi.fn(),submit:vi.fn(),selectRecount:vi.fn(),beginRecount:vi.fn(),createAttempt:vi.fn(),approveAttempt:vi.fn(),executeAttempt:vi.fn(),complete:vi.fn(),cancel:vi.fn()};
let role:'owner'|'operator'='owner';
vi.mock('../lib/workspaceContext',()=>({useWorkspace:()=>({workspace:{id:'ws',name:'Vault',role},client:{}})}));
vi.mock('../lib/cycleCountApi',async(importOriginal)=>{const actual=await importOriginal<typeof import('../lib/cycleCountApi')>();return {...actual,createCycleCountTransport:()=>api}});
const review={id:'s',public_id:'RV-CC-REVIEW',status:'review',blind_count:true,created_at:'2026-01-01',current_round_id:'r'};
const counting={...review,public_id:'RV-CC-COUNT',status:'in_progress'};
const progress={round_id:'r',round_number:2,round_type:'recount',round_status:'counting',current_round_expected_subject_count:null,current_round_observed_item_count:1,current_round_observed_lot_count:1,current_round_remaining_count:null,historical_round_count:2,total_historical_observations:4,blind:true};
afterEach(()=>cleanup());
beforeEach(()=>{vi.clearAllMocks();role='owner';api.progress.mockResolvedValue(progress);api.history.mockResolvedValue({status:'review',completion_summary:null,rounds:[{id:'r',public_id:'RV-CCR-2',round_number:2,round_type:'recount',status:'submitted',reason:'verify',subject_count:2,item_observation_count:1,lot_observation_count:1,result_count:2}]});api.attempts.mockResolvedValue([]);api.observations.mockResolvedValue([]);api.discrepancies.mockResolvedValue([])});
describe('Cycle Counts rendered states',()=>{
 it('keeps active blind recount entry free of stale resolution controls',async()=>{role='operator';api.list.mockResolvedValue([counting]);render(<CycleCounts/>);fireEvent.click(await screen.findByText('RV-CC-COUNT'));expect(await screen.findByText('Blind counting')).toBeTruthy();expect(screen.getByText('recount round 2')).toBeTruthy();expect(screen.getByLabelText('Item identifier')).toBeTruthy();expect(screen.queryByText('Current discrepancies')).toBeNull();expect(screen.getByText('Hidden')).toBeTruthy()});
 it('does not request protected history while an operator is counting',async()=>{role='operator';api.list.mockResolvedValue([counting]);render(<CycleCounts/>);fireEvent.click(await screen.findByText('RV-CC-COUNT'));await screen.findByText('Blind counting');expect(api.history).not.toHaveBeenCalled()});
 it('confirms an incomplete initial round after the structured warning',async()=>{const initial={...counting,current_round_id:'r1'};api.list.mockResolvedValue([initial]);api.progress.mockResolvedValue({...progress,round_type:'initial',round_number:1});api.submit.mockResolvedValueOnce({outcome:'confirmation_required',uncounted_item_count:2,uncounted_lot_count:1}).mockResolvedValueOnce({outcome:'submitted'});render(<CycleCounts/>);fireEvent.click(await screen.findByText('RV-CC-COUNT'));fireEvent.click(await screen.findByText('Submit current round'));expect(await screen.findByText(/2 uncounted items and 1 uncounted lots/)).toBeTruthy();fireEvent.click(screen.getByText('Confirm incomplete round'));await waitFor(()=>expect(api.submit).toHaveBeenLastCalledWith('s',true))});
 it('offers missing-item attestation during a recount',async()=>{role='operator';api.list.mockResolvedValue([counting]);api.attestItemAbsence.mockResolvedValue({outcome:'accepted'});render(<CycleCounts/>);fireEvent.click(await screen.findByText('RV-CC-COUNT'));fireEvent.change(await screen.findByLabelText('Missing item public ID'),{target:{value:'RV-ITEM-1'}});fireEvent.change(screen.getByLabelText('Absence reason'),{target:{value:'searched recount area'}});fireEvent.click(screen.getByText('Attest not found'));await waitFor(()=>expect(api.attestItemAbsence).toHaveBeenCalledWith('s','RV-ITEM-1','not_found','searched recount area',expect.any(String)))});
 it('reuses the client key after an indeterminate scanner failure',async()=>{role='operator';api.list.mockResolvedValue([counting]);api.observeItem.mockRejectedValueOnce(new Error('network interrupted')).mockResolvedValueOnce({outcome:'idempotent_replay'});render(<CycleCounts/>);fireEvent.click(await screen.findByText('RV-CC-COUNT'));fireEvent.change(await screen.findByLabelText('Item identifier'),{target:{value:'ITEM-1'}});fireEvent.change(screen.getByLabelText('Observed location'),{target:{value:'BIN-A'}});fireEvent.click(screen.getByText('Record observation'));await screen.findByText('network interrupted');fireEvent.click(screen.getByText('Record observation'));await waitFor(()=>expect(api.observeItem).toHaveBeenCalledTimes(2));expect(api.observeItem.mock.calls[0][3]).toBe(api.observeItem.mock.calls[1][3])});
 it('selects multiple discrepancies into one recount',async()=>{api.list.mockResolvedValue([review]);api.discrepancies.mockResolvedValue([{id:'d1',public_id:'D1',kind:'item_wrong_location',status:'open',classification:'confirmed_after_recount',subject_type:'item',expected_quantity:null,observed_quantity:null,computed_variance:null,post_snapshot_classification:'none',recount_outcome:'confirmed_after_recount',allowed_actions:[]},{id:'d2',public_id:'D2',kind:'lot_shortage',status:'open',classification:'changed_after_recount',subject_type:'lot',expected_quantity:10,observed_quantity:7,computed_variance:-3,post_snapshot_classification:'none',recount_outcome:'changed_after_recount',allowed_actions:[]}]);api.selectRecount.mockResolvedValue({outcome:'selected'});api.beginRecount.mockResolvedValue({outcome:'recount_started'});render(<CycleCounts/>);fireEvent.click(await screen.findByText('RV-CC-REVIEW'));fireEvent.click(await screen.findByLabelText('Select D1 for recount'));fireEvent.click(screen.getByLabelText('Select D2 for recount'));fireEvent.change(screen.getByText('Recount reason').parentElement!.querySelector('input')!,{target:{value:'verify together'}});fireEvent.click(screen.getByText('Begin one recount (2)'));await waitFor(()=>expect(api.selectRecount).toHaveBeenCalledWith('s',['d1','d2'],'verify together'));expect(api.beginRecount).toHaveBeenCalledWith('s','verify together')});
 it('locks counted destination and exposes reviewed relocation separately',async()=>{api.list.mockResolvedValue([review]);api.discrepancies.mockResolvedValue([{id:'d1',public_id:'D1',kind:'item_wrong_location',status:'open',classification:'wrong_location',subject_type:'item',expected_quantity:null,observed_quantity:null,computed_variance:null,post_snapshot_classification:'none',recount_outcome:null,allowed_actions:[{action:'item_moved_to_counted_location',reason_required:true,destination_mode:'observed',quantity_mode:'none',approval_required:false},{action:'item_moved_to_reviewed_location',reason_required:true,destination_mode:'reviewed',quantity_mode:'none',approval_required:true}]}]);render(<CycleCounts/>);fireEvent.click(await screen.findByText('RV-CC-REVIEW'));expect(await screen.findByText('Destination locked to counted location')).toBeTruthy();fireEvent.change(screen.getByLabelText('Resolution action'),{target:{value:'item_moved_to_reviewed_location'}});expect(screen.getByLabelText('Reviewed destination')).toBeTruthy()});
 it('requires acknowledgement of post-snapshot activity before resolution',async()=>{api.list.mockResolvedValue([review]);api.discrepancies.mockResolvedValue([{id:'d1',public_id:'D1',kind:'lot_shortage',status:'open',classification:'shortage',subject_type:'lot',expected_quantity:10,observed_quantity:7,computed_variance:-3,post_snapshot_classification:'quantity_changed',recount_outcome:null,allowed_actions:[{action:'lot_quantity_adjusted',reason_required:true,destination_mode:'none',quantity_mode:'latest_observed',approval_required:true}]}]);render(<CycleCounts/>);fireEvent.click(await screen.findByText('RV-CC-REVIEW'));expect(await screen.findByText(/Post-snapshot change: quantity changed/)).toBeTruthy();fireEvent.change(screen.getByLabelText('Resolution reason'),{target:{value:'verified'}});const resolve=screen.getByText('Resolve current result') as HTMLButtonElement;expect(resolve.disabled).toBe(true);fireEvent.click(screen.getByText('I reviewed the post-snapshot activity'));expect(resolve.disabled).toBe(false)});
 it('shows durable failure and retry',async()=>{api.list.mockResolvedValue([review]);api.attempts.mockResolvedValue([{id:'a',discrepancy_id:'d',action:'lot_quantity_adjusted',reason:'count',reviewed_destination_code:null,status:'failed',failure_classification:'GOVERNED_VALIDATION_FAILED',created_at:'2026-01-01',events:[]}]);api.executeAttempt.mockResolvedValue({outcome:'succeeded'});render(<CycleCounts/>);fireEvent.click(await screen.findByText('RV-CC-REVIEW'));expect(await screen.findByText(/GOVERNED_VALIDATION_FAILED/)).toBeTruthy();fireEvent.click(screen.getByText('Retry'));expect(api.executeAttempt).toHaveBeenCalledWith('a')});
 it('renders completed totals from the latest-result summary',async()=>{const completed={...review,status:'completed',public_id:'RV-CC-DONE'};api.list.mockResolvedValue([completed]);api.history.mockResolvedValue({status:'completed',completion_summary:{latest_subject_count:2,found_item_count:1,observed_lot_quantity:10,shortage_quantity:0,overage_quantity:0,net_variance:0,resolved_discrepancy_count:2,deferred_discrepancy_count:0},rounds:[]});render(<CycleCounts/>);fireEvent.click(await screen.findByText('RV-CC-DONE'));expect(await screen.findByLabelText('Latest-result completion summary')).toBeTruthy();expect(screen.getByText('Observed lot units').parentElement?.textContent).toContain('10');expect(screen.getByText(/Historical evidence is excluded/)).toBeTruthy()});
 it('only enables completion when no current discrepancy remains',async()=>{api.list.mockResolvedValue([review]);api.complete.mockResolvedValue({outcome:'completed'});render(<CycleCounts/>);fireEvent.click(await screen.findByText('RV-CC-REVIEW'));const complete=await screen.findByText('Complete cycle count') as HTMLButtonElement;expect(complete.disabled).toBe(false);fireEvent.click(complete);expect(api.complete).toHaveBeenCalledWith('s',false,'All current results reviewed')});
});
