import {beforeEach,describe,expect,it,vi} from 'vitest';
import {fireEvent,render,screen,waitFor} from '@testing-library/react';
import CycleCounts from './CycleCounts';

const api={list:vi.fn(),progress:vi.fn(),history:vi.fn(),discrepancies:vi.fn(),attempts:vi.fn(),
 observeItem:vi.fn(),observeLot:vi.fn(),attestItemAbsence:vi.fn(),submit:vi.fn(),selectRecount:vi.fn(),beginRecount:vi.fn(),createAttempt:vi.fn(),executeAttempt:vi.fn()};
let role:'owner'|'operator'='owner';
vi.mock('../lib/workspaceContext',()=>({useWorkspace:()=>({workspace:{id:'ws',name:'Vault',role},client:{}})}));
vi.mock('../lib/cycleCountApi',async(importOriginal)=>{const actual=await importOriginal<typeof import('../lib/cycleCountApi')>();return {...actual,createCycleCountTransport:()=>api}});
const review={id:'s',public_id:'RV-CC-REVIEW',status:'review',blind_count:true,created_at:'2026-01-01',current_round_id:'r'};
const counting={...review,public_id:'RV-CC-COUNT',status:'in_progress'};
const progress={round_id:'r',round_number:2,round_type:'recount',round_status:'counting',current_round_expected_subject_count:null,current_round_observed_item_count:1,current_round_observed_lot_count:1,current_round_remaining_count:null,historical_round_count:2,total_historical_observations:4,blind:true};
beforeEach(()=>{vi.clearAllMocks();role='owner';api.progress.mockResolvedValue(progress);api.history.mockResolvedValue({status:'review',completion_summary:null,rounds:[{id:'r',public_id:'RV-CCR-2',round_number:2,round_type:'recount',status:'submitted',reason:'verify',subject_count:2,item_observation_count:1,lot_observation_count:1,result_count:2}]});api.attempts.mockResolvedValue([]);api.discrepancies.mockResolvedValue([])});
describe('Cycle Counts rendered states',()=>{
 it('keeps active blind recount entry free of stale resolution controls',async()=>{role='operator';api.list.mockResolvedValue([counting]);render(<CycleCounts/>);fireEvent.click(await screen.findByText('RV-CC-COUNT'));expect(await screen.findByText('Blind counting')).toBeTruthy();expect(screen.getByText('recount round 2')).toBeTruthy();expect(screen.getByLabelText('Item identifier')).toBeTruthy();expect(screen.queryByText('Current discrepancies')).toBeNull();expect(screen.getByText('Hidden')).toBeTruthy()});
 it('selects multiple discrepancies into one recount',async()=>{api.list.mockResolvedValue([review]);api.discrepancies.mockResolvedValue([{id:'d1',public_id:'D1',kind:'item_wrong_location',status:'open',classification:'confirmed_after_recount',subject_type:'item',expected_quantity:null,observed_quantity:null,computed_variance:null,post_snapshot_classification:'none',recount_outcome:'confirmed_after_recount',allowed_actions:[]},{id:'d2',public_id:'D2',kind:'lot_shortage',status:'open',classification:'changed_after_recount',subject_type:'lot',expected_quantity:10,observed_quantity:7,computed_variance:-3,post_snapshot_classification:'none',recount_outcome:'changed_after_recount',allowed_actions:[]}]);api.selectRecount.mockResolvedValue({outcome:'selected'});api.beginRecount.mockResolvedValue({outcome:'recount_started'});render(<CycleCounts/>);fireEvent.click(await screen.findByText('RV-CC-REVIEW'));fireEvent.click(await screen.findByLabelText('Select D1 for recount'));fireEvent.click(screen.getByLabelText('Select D2 for recount'));fireEvent.change(screen.getByText('Recount reason').parentElement!.querySelector('input')!,{target:{value:'verify together'}});fireEvent.click(screen.getByText('Begin one recount (2)'));await waitFor(()=>expect(api.selectRecount).toHaveBeenCalledWith('s',['d1','d2'],'verify together'));expect(api.beginRecount).toHaveBeenCalledWith('s','verify together')});
 it('locks counted destination and exposes reviewed relocation separately',async()=>{api.list.mockResolvedValue([review]);api.discrepancies.mockResolvedValue([{id:'d1',public_id:'D1',kind:'item_wrong_location',status:'open',classification:'wrong_location',subject_type:'item',expected_quantity:null,observed_quantity:null,computed_variance:null,post_snapshot_classification:'none',recount_outcome:null,allowed_actions:[{action:'item_moved_to_counted_location',reason_required:true,destination_mode:'observed',quantity_mode:'none',approval_required:false},{action:'item_moved_to_reviewed_location',reason_required:true,destination_mode:'reviewed',quantity_mode:'none',approval_required:true}]}]);render(<CycleCounts/>);fireEvent.click(await screen.findByText('RV-CC-REVIEW'));expect(await screen.findByText('Destination locked to counted location')).toBeTruthy();fireEvent.change(screen.getByLabelText('Resolution action'),{target:{value:'item_moved_to_reviewed_location'}});expect(screen.getByLabelText('Reviewed destination')).toBeTruthy()});
 it('shows durable failure and retry',async()=>{api.list.mockResolvedValue([review]);api.attempts.mockResolvedValue([{id:'a',discrepancy_id:'d',action:'lot_quantity_adjusted',reason:'count',reviewed_destination_code:null,status:'failed',failure_classification:'GOVERNED_VALIDATION_FAILED',created_at:'2026-01-01',events:[]}]);api.executeAttempt.mockResolvedValue({outcome:'succeeded'});render(<CycleCounts/>);fireEvent.click(await screen.findByText('RV-CC-REVIEW'));expect(await screen.findByText(/GOVERNED_VALIDATION_FAILED/)).toBeTruthy();fireEvent.click(screen.getByText('Retry'));expect(api.executeAttempt).toHaveBeenCalledWith('a')});
});
