import { useEffect,useMemo,useRef,useState } from 'react';
import { ClipboardCheck,History,RefreshCw,ScanLine } from 'lucide-react';
import { useWorkspace } from '../lib/workspaceContext';
import { createCycleCountTransport,type CycleCountCompletionSummary,type CycleCountDiscrepancy,type CycleCountRoundHistory,type CycleCountSession,type ResolutionAttempt,type RoundProgress } from '../lib/cycleCountApi';
const newKey=()=>crypto.randomUUID();

export default function CycleCounts(){
 const {workspace,client}=useWorkspace();
 const api=useMemo(()=>createCycleCountTransport(client as never,()=>workspace?.id??null),[client,workspace?.id]);
 const [sessions,setSessions]=useState<readonly CycleCountSession[]>([]),[selected,setSelected]=useState<CycleCountSession|null>(null);
 const [progress,setProgress]=useState<RoundProgress|null>(null),[discrepancies,setDiscrepancies]=useState<readonly CycleCountDiscrepancy[]>([]);
 const [rounds,setRounds]=useState<readonly CycleCountRoundHistory[]>([]),[attempts,setAttempts]=useState<readonly ResolutionAttempt[]>([]);
 const [summary,setSummary]=useState<CycleCountCompletionSummary|null>(null);
 const [identifier,setIdentifier]=useState(''),[location,setLocation]=useState(''),[lot,setLot]=useState(''),[qty,setQty]=useState('');
 const [chosen,setChosen]=useState<Set<string>>(new Set()),[reason,setReason]=useState(''),[message,setMessage]=useState('');
 const loadSessions=async()=>{try{const rows=await api.list();setSessions(rows);return rows}catch(e){setMessage((e as Error).message);return [] as readonly CycleCountSession[]}};
 const loadDetail=async(session=selected)=>{if(!session)return;setProgress(await api.progress(session.id));const h=await api.history(session.id);setRounds(h.rounds);setSummary(h.completion_summary);if(session.status==='review'&&workspace?.role==='owner'){setDiscrepancies(await api.discrepancies(session.id));setAttempts(await api.attempts(session.id))}else{setDiscrepancies([]);setAttempts([])}};
 useEffect(()=>{if(workspace)void loadSessions()},[workspace?.id]);
 useEffect(()=>{void loadDetail().catch(e=>setMessage((e as Error).message))},[selected?.id,selected?.status]);
 const run=async(p:Promise<Record<string,unknown>>)=>{try{const r=await p;setMessage(String(r.outcome??'Done'));const rows=await loadSessions();const fresh=selected?rows.find(x=>x.id===selected.id)??selected:null;if(fresh!==selected)setSelected(fresh);await loadDetail(fresh);return r}catch(e){setMessage((e as Error).message)}};
 const toggle=(id:string)=>setChosen(old=>{const n=new Set(old);n.has(id)?n.delete(id):n.add(id);return n});
 const startRecount=async()=>{if(!selected||chosen.size===0)return;await run(api.selectRecount(selected.id,[...chosen],reason));await run(api.beginRecount(selected.id,reason));setChosen(new Set());setReason('')};
 return <div className="mx-auto max-w-6xl space-y-5 p-4 md:p-6">
  <header className="flex items-start justify-between"><div><h1 className="flex items-center gap-2 text-lg font-semibold"><ClipboardCheck className="h-5 w-5 text-accent"/>Cycle Counts</h1><p className="text-xs text-ink-muted">Blind, explicit-round evidence and governed review.</p></div><button onClick={()=>void loadSessions()} aria-label="Refresh cycle counts"><RefreshCw className="h-4 w-4"/></button></header>
  {message&&<div role="status" className="rounded border border-hairline bg-surface-1 p-3 text-sm">{message}</div>}
  <div className="grid gap-4 lg:grid-cols-[18rem_1fr]"><SessionList rows={sessions} selected={selected?.id} onSelect={setSelected}/><main className="space-y-4">{!selected?<Empty/>:<>
   <RoundHeader session={selected} progress={progress}/>
   {selected.status==='in_progress'?<Counting session={selected} progress={progress} identifier={identifier} location={location} lot={lot} qty={qty} setIdentifier={setIdentifier} setLocation={setLocation} setLot={setLot} setQty={setQty} run={run} api={api}/>:null}
   {selected.status==='review'&&workspace?.role==='owner'?<Review session={selected} discrepancies={discrepancies} attempts={attempts} chosen={chosen} toggle={toggle} reason={reason} setReason={setReason} startRecount={startRecount} run={run} api={api}/>:null}
   {selected.status==='completed'&&summary?<CompletionSummary summary={summary}/>:null}
   <HistoryPanel rounds={rounds}/>
  </>}</main></div>
 </div>;
}

function SessionList({rows,selected,onSelect}:{rows:readonly CycleCountSession[];selected?:string;onSelect:(s:CycleCountSession)=>void}){return <aside className="rounded-lg border border-hairline bg-surface-1 p-3"><h2 className="mb-2 text-sm font-semibold">Sessions</h2>{rows.length===0?<p className="text-sm text-ink-muted">No cycle counts.</p>:rows.map(s=><button key={s.id} onClick={()=>onSelect(s)} className={`mb-2 w-full rounded border p-3 text-left ${selected===s.id?'border-accent bg-accent/5':'border-hairline'}`}><div className="font-medium">{s.public_id}</div><div className="text-xs text-ink-muted">{s.status} · {s.blind_count?'Blind':'Visible'}</div></button>)}</aside>}
function Empty(){return <div className="rounded border border-hairline p-8 text-center text-sm text-ink-muted">Choose a session.</div>}
function RoundHeader({session,progress}:{session:CycleCountSession;progress:RoundProgress|null}){return <section className="rounded-lg border border-hairline bg-surface-1 p-4"><div className="flex items-center justify-between"><div><h2 className="font-semibold">{session.public_id}</h2><p className="text-xs text-ink-muted">{progress?`${progress.round_type} round ${progress.round_number}`:'Loading round…'}</p></div>{progress?.blind&&<span className="rounded-full bg-warning/15 px-2 py-1 text-xs font-semibold">Blind counting</span>}</div>{progress&&<div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4"><Metric label="Items observed" value={progress.current_round_observed_item_count}/><Metric label="Lots observed" value={progress.current_round_observed_lot_count}/><Metric label="Remaining" value={progress.current_round_remaining_count??'Hidden'}/><Metric label="Rounds" value={progress.historical_round_count}/></div>}</section>}
function Counting({session,identifier,location,lot,qty,setIdentifier,setLocation,setLot,setQty,run,api}:{session:CycleCountSession;progress:RoundProgress|null;identifier:string;location:string;lot:string;qty:string;setIdentifier:(x:string)=>void;setLocation:(x:string)=>void;setLot:(x:string)=>void;setQty:(x:string)=>void;run:(p:Promise<Record<string,unknown>>)=>Promise<unknown>;api:ReturnType<typeof createCycleCountTransport>}){const itemKey=useRef(newKey()),lotKey=useRef(newKey());const observeItem=async()=>{const result=await run(api.observeItem(session.id,identifier,location,itemKey.current));if(result)itemKey.current=newKey()};const observeLot=async()=>{const result=await run(api.observeLot(session.id,lot,Number(qty),lotKey.current));if(result)lotKey.current=newKey()};return <section className="grid gap-4 md:grid-cols-2"><form className="rounded-lg border border-hairline p-4" onSubmit={e=>{e.preventDefault();void observeItem()}}><h3 className="mb-3 flex gap-2 font-semibold"><ScanLine className="h-4 w-4"/>Serialized observation</h3><input aria-label="Item identifier" required value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="Scan identifier" className="mb-2 w-full rounded border border-hairline p-2"/><input aria-label="Observed location" required value={location} onChange={e=>setLocation(e.target.value)} placeholder="Location code" className="mb-3 w-full rounded border border-hairline p-2"/><button className="rounded bg-accent px-3 py-2 text-sm text-white">Record observation</button></form><form className="rounded-lg border border-hairline p-4" onSubmit={e=>{e.preventDefault();void observeLot()}}><h3 className="mb-3 font-semibold">Lot observation</h3><input aria-label="Lot public ID" required value={lot} onChange={e=>setLot(e.target.value)} placeholder="Lot ID" className="mb-2 w-full rounded border border-hairline p-2"/><input aria-label="Observed quantity" required type="number" min="0" value={qty} onChange={e=>setQty(e.target.value)} placeholder="Quantity" className="mb-3 w-full rounded border border-hairline p-2"/><button className="rounded bg-accent px-3 py-2 text-sm text-white">Record lot</button></form><button onClick={()=>void run(api.submit(session.id,false))} className="rounded border border-accent px-3 py-2 text-sm font-semibold text-accent">Submit current round</button></section>}
function Review({session,discrepancies,attempts,chosen,toggle,reason,setReason,startRecount,run,api}:{session:CycleCountSession;discrepancies:readonly CycleCountDiscrepancy[];attempts:readonly ResolutionAttempt[];chosen:Set<string>;toggle:(x:string)=>void;reason:string;setReason:(x:string)=>void;startRecount:()=>Promise<void>;run:(p:Promise<Record<string,unknown>>)=>Promise<unknown>;api:ReturnType<typeof createCycleCountTransport>}){return <section className="space-y-3 rounded-lg border border-hairline p-4"><h3 className="font-semibold">Current discrepancies</h3>{discrepancies.length===0?<p className="text-sm text-ink-muted">No current discrepancies.</p>:discrepancies.map(d=><DiscrepancyCard key={d.id} d={d} checked={chosen.has(d.id)} toggle={()=>toggle(d.id)} run={run} api={api}/>) }{discrepancies.length>0&&<div className="rounded bg-surface-2 p-3"><label className="text-xs font-medium">Recount reason</label><input value={reason} onChange={e=>setReason(e.target.value)} className="mt-1 w-full rounded border border-hairline p-2"/><button disabled={chosen.size===0||!reason.trim()} onClick={()=>void startRecount()} className="mt-2 rounded bg-accent px-3 py-2 text-sm text-white disabled:opacity-50">Begin one recount ({chosen.size})</button></div>}<h3 className="pt-2 font-semibold">Resolution attempts</h3>{attempts.length===0?<p className="text-sm text-ink-muted">No resolution attempts.</p>:attempts.map(a=><div key={a.id} className="flex items-center justify-between rounded border border-hairline p-3 text-sm"><span>{a.action.replaceAll('_',' ')} · {a.status}{a.failure_classification?` · ${a.failure_classification}`:''}</span>{a.status==='failed'&&<button onClick={()=>void run(api.executeAttempt(a.id))} className="rounded border border-hairline px-2 py-1">Retry</button>}</div>)}<div className="flex justify-end border-t border-hairline pt-3"><button disabled={discrepancies.length>0} onClick={()=>void run(api.complete(session.id,false,'All current results reviewed'))} className="rounded bg-accent px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Complete cycle count</button></div></section>}
function DiscrepancyCard({d,checked,toggle,run,api}:{d:CycleCountDiscrepancy;checked:boolean;toggle:()=>void;run:(p:Promise<Record<string,unknown>>)=>Promise<unknown>;api:ReturnType<typeof createCycleCountTransport>}){const [action,setAction]=useState(d.allowed_actions[0]?.action??''),[reason,setReason]=useState(''),[destination,setDestination]=useState('');const rule=d.allowed_actions.find(x=>x.action===action);return <article className="rounded border border-hairline p-3"><div className="flex gap-3"><input aria-label={`Select ${d.public_id} for recount`} type="checkbox" checked={checked} onChange={toggle}/><div className="flex-1"><div className="font-medium">{d.kind.replaceAll('_',' ')}</div><div className="text-xs text-ink-muted">{d.classification.replaceAll('_',' ')}{d.observed_quantity!==null?` · observed ${d.observed_quantity}`:''}{d.computed_variance!==null?` · variance ${d.computed_variance}`:''}</div></div></div><div className="mt-3 grid gap-2 md:grid-cols-3"><select aria-label="Resolution action" value={action} onChange={e=>setAction(e.target.value)} className="rounded border border-hairline p-2 text-sm">{d.allowed_actions.map(a=><option key={a.action} value={a.action}>{a.action.replaceAll('_',' ')}</option>)}</select><input aria-label="Resolution reason" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason" className="rounded border border-hairline p-2 text-sm"/>{rule?.destination_mode==='reviewed'?<input aria-label="Reviewed destination" value={destination} onChange={e=>setDestination(e.target.value)} placeholder="Destination code" className="rounded border border-hairline p-2 text-sm"/>:<div className="p-2 text-xs text-ink-muted">{rule?.destination_mode==='observed'?'Destination locked to counted location':'No destination required'}</div>}</div><button disabled={!action||(rule?.reason_required&&!reason.trim())} onClick={async()=>{const r=await run(api.createAttempt(d.id,action,reason,rule?.destination_mode==='reviewed'?destination:null,newKey())) as Record<string,unknown>|undefined;if(r?.attempt_id)await run(api.executeAttempt(String(r.attempt_id)))} } className="mt-2 rounded border border-accent px-3 py-1.5 text-sm text-accent disabled:opacity-50">Resolve current result</button></article>}
function HistoryPanel({rounds}:{rounds:readonly CycleCountRoundHistory[]}){return <section className="rounded-lg border border-hairline p-4"><h3 className="flex items-center gap-2 font-semibold"><History className="h-4 w-4"/>Round and evidence history</h3><div className="mt-3 space-y-2">{rounds.map(r=><div key={r.id} className="rounded bg-surface-2 p-3 text-sm"><b>Round {r.round_number} · {r.round_type}</b><div className="text-xs text-ink-muted">{r.status} · {r.subject_count} subjects · {r.item_observation_count} item and {r.lot_observation_count} lot observations · {r.result_count} results</div></div>)}</div></section>}
function CompletionSummary({summary}:{summary:CycleCountCompletionSummary}){return <section aria-label="Latest-result completion summary" className="rounded-lg border border-hairline bg-surface-1 p-4"><h3 className="font-semibold">Completed latest-result summary</h3><p className="mt-1 text-xs text-ink-muted">Each subject contributes only its latest accepted round result. Historical evidence is excluded from inventory totals.</p><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4"><Metric label="Latest subjects" value={summary.latest_subject_count}/><Metric label="Found items" value={summary.found_item_count}/><Metric label="Observed lot units" value={summary.observed_lot_quantity}/><Metric label="Net variance" value={summary.net_variance}/><Metric label="Shortage units" value={summary.shortage_quantity}/><Metric label="Overage units" value={summary.overage_quantity}/><Metric label="Resolved" value={summary.resolved_discrepancy_count}/><Metric label="Deferred" value={summary.deferred_discrepancy_count}/></div></section>}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded bg-surface-2 p-3"><div className="text-xs text-ink-muted">{label}</div><div className="text-lg font-semibold">{value}</div></div>}
