import { afterAll,beforeAll,beforeEach,describe,expect,it } from 'vitest';
import express from 'express';import type { Server } from 'node:http';
import { setCallerClientFactoryForTests } from '../provenance/auth.js';
const {default:router}=await import('./cycleCounts.js');
const WS='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',SID='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';
const identities:Record<string,{id:string;role?:string}>={owner:{id:'owner',role:'owner'},operator:{id:'operator',role:'operator'},viewer:{id:'viewer',role:'viewer'},stranger:{id:'stranger'}};
let calls:Array<{fn:string;args:Record<string,unknown>}>=[];
function fake(token:string){const who=identities[token];return {auth:{getUser:async()=>who?{data:{user:{id:who.id}},error:null}:{data:{user:null},error:{message:'bad'}}},from(table:string){const q:any={select:()=>q,eq:()=>q,order:async()=>({data:table==='workspace_members'&&who?.role?[{role:who.role}]:table==='cycle_count_sessions'?[{id:SID,public_id:'RV-CC-TEST01',status:'in_progress',blind_count:true}]:[],error:null}),limit:async()=>({data:who?.role?[{role:who.role}]:[],error:null}),then:(resolve:(v:unknown)=>unknown)=>Promise.resolve(resolve({data:who?.role?[{role:who.role}]:[],error:null}))};return q},rpc:async(fn:string,args:Record<string,unknown>)=>{calls.push({fn,args});return {data:{outcome:'ok'},error:null}}};}
let server:Server,base:string;
beforeAll(async()=>{const app=express();app.use(express.json());app.use('/api/cycle-counts',router);await new Promise<void>(resolve=>{server=app.listen(0,'127.0.0.1',()=>{const a=server.address();base=`http://127.0.0.1:${typeof a==='object'&&a?a.port:0}`;resolve()})});setCallerClientFactoryForTests(t=>fake(t) as never)});
afterAll(()=>{server.close();setCallerClientFactoryForTests(null)});beforeEach(()=>{calls=[];process.env.SHADOW_IMPORT='repository-fixtures';process.env.SUPABASE_URL='http://127.0.0.1';process.env.SUPABASE_ANON_KEY='test'});
async function call(method:string,path:string,token?:string,b?:unknown){return fetch(base+path,{method,headers:{...(token?{authorization:`Bearer ${token}`}:{}) ,...(b?{'content-type':'application/json'}:{})},body:b?JSON.stringify(b):undefined})}
describe('cycle count routes',()=>{
 it('is absent when shadow surfaces are disabled',async()=>{delete process.env.SHADOW_IMPORT;expect((await call('GET',`/api/cycle-counts/sessions?workspaceId=${WS}`,'owner')).status).toBe(404)});
 it('requires authentication and membership',async()=>{expect((await call('GET',`/api/cycle-counts/sessions?workspaceId=${WS}`)).status).toBe(401);expect((await call('GET',`/api/cycle-counts/sessions?workspaceId=${WS}`,'stranger')).status).toBe(403)});
 it('allows member session history but keeps counting operator-only',async()=>{expect((await call('GET',`/api/cycle-counts/sessions?workspaceId=${WS}`,'viewer')).status).toBe(200);expect((await call('POST',`/api/cycle-counts/${SID}/items`,'viewer',{workspaceId:WS})).status).toBe(403)});
 it('forwards a client key to the governed item RPC',async()=>{const k='cccccccc-cccc-cccc-cccc-cccccccccccc';expect((await call('POST',`/api/cycle-counts/${SID}/items`,'operator',{workspaceId:WS,identifier:'SCAN',locationCode:'BIN-A',idempotencyKey:k})).status).toBe(200);expect(calls[0]).toMatchObject({fn:'observe_cycle_count_item',args:{p_workspace_id:WS,p_session_id:SID,p_idempotency_key:k}})});
 it('keeps recount and resolution owner-only',async()=>{expect((await call('POST',`/api/cycle-counts/${SID}/recount`,'operator',{workspaceId:WS,reason:'verify'})).status).toBe(403);expect((await call('POST',`/api/cycle-counts/${SID}/recount`,'owner',{workspaceId:WS,reason:'verify'})).status).toBe(200);expect(calls[0].fn).toBe('begin_cycle_count_recount')});
 it('allows member evidence history but keeps discrepancy answers owner-only',async()=>{expect((await call('GET',`/api/cycle-counts/${SID}/history?workspaceId=${WS}`,'viewer')).status).toBe(200);expect((await call('GET',`/api/cycle-counts/${SID}/discrepancies?workspaceId=${WS}`,'operator')).status).toBe(403);expect((await call('GET',`/api/cycle-counts/${SID}/discrepancies?workspaceId=${WS}`,'owner')).status).toBe(200);expect(calls.map(x=>x.fn)).toEqual(['list_cycle_count_history','list_current_cycle_count_discrepancies'])});
});
