// Generator for supabase/tests/18_inventory_fixture_mapping.sql.
//
// Maps the repository inventory fixture through the real Phase 5 identity
// registrars and proves the invariants the acceptance requires: exactly 1,487
// lot public ids preserved, lot grain intact, every lot bound to one sellable
// SKU, deterministic product/SKU dedup counts, serialized children only for the
// source-serialized (graded) rows, and no lot/item double counting. Regenerate:
//
//   npx tsx server/scripts/genInventoryFixtureMapping.ts
//
// The .sql it writes is committed and runs in BOTH db:test tiers.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  buildInventoryIdentityPlan,
  type InventoryFixtureRow,
  type PlannedProduct,
} from '../src/inventory/adapter.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..', '..');
const OUT = join(ROOT, 'supabase', 'tests', '18_inventory_fixture_mapping.sql');

function q(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}
function qn(s: string | null): string {
  return s === null ? 'null' : q(s);
}

function main(): void {
  const rows = JSON.parse(
    readFileSync(join(ROOT, 'server', 'seed', 'inventory.json'), 'utf8')
  ) as InventoryFixtureRow[];
  const plan = buildInventoryIdentityPlan(rows);
  const productByKey = new Map<string, PlannedProduct>(plan.products.map((p) => [p.canonicalKey, p]));
  const skuByFingerprint = new Map(plan.skus.map((s) => [s.fingerprint, s]));

  const values: string[] = [];
  for (const lot of plan.lots) {
    const p = productByKey.get(lot.productKey);
    if (!p) throw new Error(`no product for ${lot.publicId}`);
    const sku = skuByFingerprint.get(lot.fingerprint);
    if (!sku) throw new Error(`no sku for ${lot.publicId}`);
    const a = sku.attrs;
    const pa = p.attrs;
    values.push(
      `(${q(lot.publicId)},${q(p.vertical)},${q(lot.productKey)},${q(p.displayName)},` +
        `${qn(pa['set_name'])},${qn(pa['card_number'])},${qn(pa['featured_subject'])},${qn(pa['language'])},` +
        `${qn(a['condition_or_quality'] ?? null)},${qn(a['grading_company'] ?? null)},` +
        `${qn(a['numeric_grade'] ?? null)},${qn(a['grade_designation'] ?? null)},` +
        `${qn(a['seal_or_packaging_condition'] ?? null)},${qn(a['product_format'] ?? null)},` +
        `${q(lot.trackingMode)},${lot.quantity},${qn(lot.locationCode)},${qn(lot.recordOrigin)},` +
        `${qn(lot.serialized?.certificateNumber ?? null)},${qn(lot.serialized?.serialNumber ?? null)})`
    );
  }

  const sql = `-- Phase 5 inventory fixture mapping — GENERATED by
-- server/scripts/genInventoryFixtureMapping.ts. DO NOT EDIT BY HAND; regenerate.
--
-- Stages all ${plan.expectedLots} repository inventory lots through the real
-- identity registrars and proves lot-id preservation, lot grain, one-SKU-per-lot,
-- deterministic product/SKU counts, serialized-only-when-graded, and no double
-- counting. Runs in both db:test tiers.
begin;
create extension if not exists pgtap;
select plan(11);

create function pg_temp.login(p_uid uuid) returns void language plpgsql as $$
begin
  perform set_config('request.jwt.claim.sub', p_uid::text, true);
  perform set_config('request.jwt.claims',
    json_build_object('sub', p_uid, 'role', 'authenticated')::text, true);
  execute 'set local role authenticated';
end $$;
create function pg_temp.logout() returns void language plpgsql as $$
begin
  execute 'reset role';
  perform set_config('request.jwt.claim.sub', '', true);
  perform set_config('request.jwt.claims', '', true);
end $$;

insert into auth.users (id, email) values
  ('a1111111-1111-1111-1111-111111111111', 'owner@example.test'),
  ('a2222222-2222-2222-2222-222222222222', 'operator@example.test');
insert into public.workspaces (id, name, created_by) values
  ('aaaa0000-0000-4000-8000-000000000001', 'WS A', 'a1111111-1111-1111-1111-111111111111');
insert into public.workspace_members (workspace_id, user_id, role) values
  ('aaaa0000-0000-4000-8000-000000000001', 'a2222222-2222-2222-2222-222222222222', 'operator');

create temp table plan_rows (
  lot_public_id text, vertical text, product_key text, product_display text,
  set_name text, card_number text, subject text, language text,
  condition_or_quality text, grading_company text, numeric_grade text, grade_designation text,
  seal text, product_format text, tracking_mode text, quantity integer, location_code text,
  record_origin text, cert text, serial text
);
grant all on table plan_rows to public;
insert into plan_rows values
${values.join(',\n')};

-- Map the entire fixture through the governed registrars, as the operator.
select pg_temp.login('a2222222-2222-2222-2222-222222222222');
do $body$
declare
  v_ws uuid := 'aaaa0000-0000-4000-8000-000000000001';
  r record;
  v_prod uuid;
  v_sku uuid;
  v_lot uuid;
begin
  for r in select * from plan_rows order by lot_public_id loop
    if r.location_code is not null then
      perform public.register_storage_location(v_ws, r.location_code, null, null);
    end if;
    v_prod := (public.register_product(v_ws, r.vertical, r.product_display, r.product_key,
      jsonb_build_object('set_name', r.set_name, 'card_number', r.card_number,
        'featured_subject', r.subject, 'language', r.language))->>'id')::uuid;
    v_sku := (public.register_sellable_sku(v_ws, v_prod,
      jsonb_build_object('condition_or_quality', r.condition_or_quality, 'grading_company', r.grading_company,
        'numeric_grade', r.numeric_grade, 'grade_designation', r.grade_designation,
        'seal_or_packaging_condition', r.seal, 'product_format', r.product_format))->>'id')::uuid;
    v_lot := (public.stage_inventory_lot(v_ws, r.lot_public_id, v_sku, r.tracking_mode, r.quantity,
      r.location_code, r.record_origin, '1.0.0',
      jsonb_build_object('condition_or_quality', r.condition_or_quality, 'grading_company', r.grading_company,
        'numeric_grade', r.numeric_grade, 'grade_designation', r.grade_designation,
        'product_format', r.product_format))->>'id')::uuid;
    if r.tracking_mode = 'serialized' then
      perform public.mint_serialized_item(v_ws, v_lot, r.grading_company, r.cert, r.serial);
    end if;
  end loop;
end
$body$;
select pg_temp.logout();

-- === Invariants ===
select is((select count(*)::int from public.inventory_lots), ${plan.expectedLots},
  'exactly ${plan.expectedLots} inventory lots exist (lot grain preserved)');
select is((select count(distinct public_id)::int from public.inventory_lots), ${plan.expectedLots},
  'all ${plan.expectedLots} lot public ids are distinct');
select is(
  (select count(*)::int from plan_rows p
   where not exists (select 1 from public.inventory_lots l where l.public_id = p.lot_public_id)),
  0, 'every fixture lot public id is preserved verbatim');
select is((select count(*)::int from public.inventory_lots where public_id !~ '^RV-[CS]-[0-9]{4,6}$'),
  0, 'every lot id keeps its RV-C / RV-S shape');
select is((select count(*)::int from public.inventory_lots where sku_id is null), 0,
  'every lot references exactly one sellable SKU');
select is((select count(*)::int from public.product_catalog), ${plan.expectedProducts},
  'deterministic product count');
select is((select count(*)::int from public.sellable_skus), ${plan.expectedSkus},
  'deterministic sellable-SKU count');
select is((select count(*)::int from public.inventory_items), ${plan.expectedSerializedItems},
  'serialized items exist only for the ${plan.expectedSerializedItems} graded lots');
select is(
  (select count(*)::int from public.inventory_lots l
   where l.tracking_mode = 'lot_managed'
     and exists (select 1 from public.inventory_items it where it.lot_id = l.id)),
  0, 'no lot-managed lot has serialized children (no double counting)');
select is((select count(*)::int from public.storage_locations), ${plan.expectedLocations},
  'deterministic storage-location count');
select is((select count(distinct scan_sku)::int from public.inventory_items),
  ${plan.expectedSerializedItems}, 'every serialized item has a distinct opaque scan SKU');

select * from finish();
rollback;
`;

  writeFileSync(OUT, sql);
  process.stdout.write(
    `wrote ${OUT}\n  lots=${plan.expectedLots} products=${plan.expectedProducts} ` +
      `skus=${plan.expectedSkus} serialized=${plan.expectedSerializedItems} ` +
      `locations=${plan.expectedLocations} ambiguities=${plan.ambiguities.length}\n`
  );
}

main();
