-- S1.4 committed acquisition detail, payment events, and inbound shipment governance.
create type public.acquisition_payment_instrument as enum ('card','bank','balance','credit','cash','other');
create type public.acquisition_shipment_status as enum ('expected','in_transit','delivered','lost','cancelled');

alter table public.audit_events drop constraint audit_events_event_type_check;
alter table public.audit_events add constraint audit_events_event_type_check check (event_type in (
  'source_system_registered','import_previewed','import_started','import_records_staged','import_committed','import_failed','source_record_ingested','crosswalk_candidate_created','crosswalk_confirmed','crosswalk_rejected','crosswalk_superseded','issue_opened','issue_acknowledged','issue_resolved','issue_wont_fix','channel_registered','supplier_registered','supplier_alias_created','acquisition_import_started','acquisition_import_staged','acquisition_import_committed','acquisition_import_failed','lot_line_superseded','cost_component_reversed','cost_allocation_proposed','cost_allocation_confirmed','cost_allocation_reversed','acquisition_line_classified','acquisition_line_classification_superseded','acquisition_line_classification_overridden','classification_rule_created','classification_rule_superseded',
  'acquisition_payment_recorded','acquisition_payment_reversed','acquisition_shipment_created','acquisition_shipment_transitioned'
));

create table public.acquisition_payments (
 id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete restrict,
 public_id text not null default app.mint_governed_public_id('RV-APAY') check(public_id ~ '^RV-APAY-[A-Z0-9]{6,20}$'), acquisition_order_id uuid not null,
 paid_at timestamptz not null, amount_minor bigint not null check(amount_minor>0), currency text not null check(currency ~ '^[A-Z]{3}$'), instrument public.acquisition_payment_instrument not null,
 external_reference text check(external_reference is null or char_length(external_reference) between 1 and 200), source_record_id uuid,
 evidence_note text check(evidence_note is null or char_length(evidence_note)<=1000), idempotency_key text not null check(char_length(idempotency_key) between 8 and 200), payload_fingerprint text not null,
 reversed_at timestamptz, reversed_by uuid references auth.users(id), reversal_reason text check(reversal_reason is null or char_length(reversal_reason) between 1 and 500), reversal_idempotency_key text,
 created_by uuid not null references auth.users(id), created_at timestamptz not null default now(),
 unique(id,workspace_id), unique(workspace_id,public_id), unique(workspace_id,idempotency_key),
 foreign key(acquisition_order_id,workspace_id) references public.acquisition_orders(id,workspace_id) on delete restrict,
 foreign key(source_record_id,workspace_id) references public.source_records(id,workspace_id) on delete restrict,
 check((reversed_at is null)=(reversed_by is null) and (reversed_at is null)=(reversal_reason is null) and (reversed_at is null)=(reversal_idempotency_key is null))
);
create unique index acquisition_payments_active_external_uidx on public.acquisition_payments(workspace_id,lower(external_reference)) where external_reference is not null and reversed_at is null;

create table public.acquisition_shipments (
 id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete restrict,
 public_id text not null default app.mint_governed_public_id('RV-ASHIP') check(public_id ~ '^RV-ASHIP-[A-Z0-9]{6,20}$'), acquisition_order_id uuid not null,
 carrier text check(carrier is null or char_length(carrier) between 1 and 100), tracking_number text check(tracking_number is null or char_length(tracking_number) between 1 and 200),
 shipped_at timestamptz, expected_at timestamptz, received_at timestamptz, status public.acquisition_shipment_status not null default 'expected',
 shipping_cost_minor bigint check(shipping_cost_minor>=0), currency text check(currency is null or currency ~ '^[A-Z]{3}$'), source_record_id uuid,
 evidence_note text check(evidence_note is null or char_length(evidence_note)<=1000), create_idempotency_key text not null check(char_length(create_idempotency_key) between 8 and 200), create_fingerprint text not null,
 transition_idempotency_key text, transition_fingerprint text, transition_reason text,
 created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(id,workspace_id), unique(workspace_id,public_id), unique(workspace_id,create_idempotency_key),
 foreign key(acquisition_order_id,workspace_id) references public.acquisition_orders(id,workspace_id) on delete restrict,
 foreign key(source_record_id,workspace_id) references public.source_records(id,workspace_id) on delete restrict,
 check(shipping_cost_minor is null or currency is not null), check(expected_at is null or shipped_at is null or expected_at>=shipped_at),
 check((status='delivered' and received_at is not null) or (status<>'delivered' and received_at is null))
);
create unique index acquisition_shipments_tracking_uidx on public.acquisition_shipments(workspace_id,lower(carrier),lower(regexp_replace(tracking_number,'[[:space:]-]','','g'))) where carrier is not null and tracking_number is not null;

create function app.guard_acquisition_event_rows() returns trigger language plpgsql set search_path='' as $$ begin
 if current_setting('app.governed_acquisition_mutation',true)<>'on' then raise exception 'governed_write_required' using errcode='42501'; end if; return coalesce(new,old); end $$;
create trigger acquisition_payments_guard before update or delete on public.acquisition_payments for each row execute function app.guard_acquisition_event_rows();
create trigger acquisition_shipments_guard before update or delete on public.acquisition_shipments for each row execute function app.guard_acquisition_event_rows();
revoke all on function app.guard_acquisition_event_rows() from public;

alter table public.acquisition_payments enable row level security; alter table public.acquisition_shipments enable row level security;
create policy acquisition_payments_member_read on public.acquisition_payments for select to authenticated using(exists(select 1 from public.workspace_members m where m.workspace_id=acquisition_payments.workspace_id and m.user_id=auth.uid()));
create policy acquisition_shipments_member_read on public.acquisition_shipments for select to authenticated using(exists(select 1 from public.workspace_members m where m.workspace_id=acquisition_shipments.workspace_id and m.user_id=auth.uid()));
revoke all on public.acquisition_payments,public.acquisition_shipments from public,anon,authenticated;
grant select on public.acquisition_payments,public.acquisition_shipments to authenticated;

create function public.record_acquisition_payment(p_workspace_id uuid,p_acquisition_order_public_id text,p_paid_at timestamptz,p_amount_minor bigint,p_currency text,p_instrument text,p_external_reference text default null,p_source_record_id uuid default null,p_evidence_note text default null,p_idempotency_key text default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare u uuid; o public.acquisition_orders%rowtype; x public.acquisition_payments%rowtype; fp text; ext text:=nullif(btrim(p_external_reference),''); note text:=nullif(btrim(p_evidence_note),''); key text:=btrim(coalesce(p_idempotency_key,''));
begin
 u:=app.assert_workspace_role(p_workspace_id,array['owner','operator']::public.workspace_role[]);
 if p_paid_at is null or p_amount_minor is null or p_amount_minor<=0 then raise exception 'invalid_amount' using errcode='22023'; end if;
 if p_currency !~ '^[A-Z]{3}$' then raise exception 'invalid_currency' using errcode='22023'; end if;
 if p_instrument not in ('card','bank','balance','credit','cash','other') then raise exception 'invalid_instrument' using errcode='22023'; end if;
 if char_length(key) not between 8 and 200 or char_length(coalesce(ext,''))>200 or char_length(coalesce(note,''))>1000 then raise exception 'invalid_request' using errcode='22023'; end if;
 select a.* into o from public.acquisition_orders a join public.acquisition_import_jobs j on j.id=a.acquisition_import_job_id and j.workspace_id=a.workspace_id and j.status='committed' where a.workspace_id=p_workspace_id and a.public_id=p_acquisition_order_public_id;
 if o.id is null then raise exception 'acquisition_not_found' using errcode='P0002'; end if;
 fp:=encode(digest(concat_ws('|',o.id,p_paid_at,p_amount_minor,p_currency,p_instrument,ext,p_source_record_id,note),'sha256'),'hex'); perform pg_advisory_xact_lock(hashtextextended(p_workspace_id::text||key,0));
 select * into x from public.acquisition_payments where workspace_id=p_workspace_id and idempotency_key=key;
 if x.id is not null then if x.payload_fingerprint<>fp then raise exception 'idempotency_conflict' using errcode='23505'; end if; return jsonb_build_object('paymentPublicId',x.public_id,'replayed',true); end if;
 begin insert into public.acquisition_payments(workspace_id,acquisition_order_id,paid_at,amount_minor,currency,instrument,external_reference,source_record_id,evidence_note,idempotency_key,payload_fingerprint,created_by) values(p_workspace_id,o.id,p_paid_at,p_amount_minor,p_currency,p_instrument::public.acquisition_payment_instrument,ext,p_source_record_id,note,key,fp,u) returning * into x; exception when unique_violation or foreign_key_violation then raise exception 'idempotency_conflict' using errcode='23505'; end;
 perform app.log_audit_event(p_workspace_id,'acquisition_payment_recorded','acquisition_payments',x.id,u,'acquisition.payment',null,p_source_record_id,null,jsonb_build_object('payment_public_id',x.public_id,'order_public_id',o.public_id,'amount_minor',p_amount_minor,'currency',p_currency));
 return jsonb_build_object('paymentPublicId',x.public_id,'replayed',false);
end $$;

create function public.reverse_acquisition_payment(p_workspace_id uuid,p_payment_public_id text,p_reason text,p_idempotency_key text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare u uuid; x public.acquisition_payments%rowtype; reason text:=btrim(coalesce(p_reason,'')); key text:=btrim(coalesce(p_idempotency_key,'')); begin
 u:=app.assert_workspace_role(p_workspace_id,array['owner']::public.workspace_role[]); if char_length(reason) not between 1 and 500 or char_length(key) not between 8 and 200 then raise exception 'invalid_request' using errcode='22023'; end if;
 select * into x from public.acquisition_payments where workspace_id=p_workspace_id and public_id=p_payment_public_id for update; if x.id is null then raise exception 'payment_not_found' using errcode='P0002'; end if;
 if x.reversed_at is not null then if x.reversal_idempotency_key=key and x.reversal_reason=reason then return jsonb_build_object('paymentPublicId',x.public_id,'replayed',true,'state','reversed'); end if; raise exception 'already_reversed' using errcode='23505'; end if;
 perform set_config('app.governed_acquisition_mutation','on',true); update public.acquisition_payments set reversed_at=now(),reversed_by=u,reversal_reason=reason,reversal_idempotency_key=key where id=x.id returning * into x;
 perform app.log_audit_event(p_workspace_id,'acquisition_payment_reversed','acquisition_payments',x.id,u,'acquisition.payment',null,x.source_record_id,null,jsonb_build_object('payment_public_id',x.public_id,'reason',reason)); return jsonb_build_object('paymentPublicId',x.public_id,'replayed',false,'state','reversed'); end $$;

create function public.create_acquisition_shipment(p_workspace_id uuid,p_acquisition_order_public_id text,p_carrier text default null,p_tracking_number text default null,p_shipped_at timestamptz default null,p_expected_at timestamptz default null,p_status text default 'expected',p_shipping_cost_minor bigint default null,p_currency text default null,p_source_record_id uuid default null,p_evidence_note text default null,p_idempotency_key text default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare u uuid; o public.acquisition_orders%rowtype; x public.acquisition_shipments%rowtype; car text:=nullif(btrim(p_carrier),''); track text:=nullif(btrim(p_tracking_number),''); note text:=nullif(btrim(p_evidence_note),''); key text:=btrim(coalesce(p_idempotency_key,'')); fp text; recv timestamptz; begin
 u:=app.assert_workspace_role(p_workspace_id,array['owner','operator']::public.workspace_role[]); if p_status not in ('expected','in_transit','delivered','lost','cancelled') or char_length(key) not between 8 and 200 then raise exception 'invalid_request' using errcode='22023'; end if; if p_shipping_cost_minor is not null and (p_shipping_cost_minor<0 or p_currency !~ '^[A-Z]{3}$') then raise exception 'invalid_currency' using errcode='22023'; end if; if p_expected_at is not null and p_shipped_at is not null and p_expected_at<p_shipped_at then raise exception 'invalid_request' using errcode='22023'; end if;
 select a.* into o from public.acquisition_orders a join public.acquisition_import_jobs j on j.id=a.acquisition_import_job_id and j.workspace_id=a.workspace_id and j.status='committed' where a.workspace_id=p_workspace_id and a.public_id=p_acquisition_order_public_id; if o.id is null then raise exception 'acquisition_not_found' using errcode='P0002'; end if;
 recv:=case when p_status='delivered' then now() else null end; fp:=encode(digest(concat_ws('|',o.id,lower(car),lower(regexp_replace(track,'[[:space:]-]','','g')),p_shipped_at,p_expected_at,p_status,p_shipping_cost_minor,p_currency,p_source_record_id,note),'sha256'),'hex'); perform pg_advisory_xact_lock(hashtextextended(p_workspace_id::text||key,0)); select * into x from public.acquisition_shipments where workspace_id=p_workspace_id and create_idempotency_key=key; if x.id is not null then if x.create_fingerprint<>fp then raise exception 'idempotency_conflict' using errcode='23505'; end if; return jsonb_build_object('shipmentPublicId',x.public_id,'status',x.status,'replayed',true); end if;
 begin insert into public.acquisition_shipments(workspace_id,acquisition_order_id,carrier,tracking_number,shipped_at,expected_at,received_at,status,shipping_cost_minor,currency,source_record_id,evidence_note,create_idempotency_key,create_fingerprint,created_by) values(p_workspace_id,o.id,car,track,p_shipped_at,p_expected_at,recv,p_status::public.acquisition_shipment_status,p_shipping_cost_minor,p_currency,p_source_record_id,note,key,fp,u) returning * into x; exception when unique_violation or foreign_key_violation then raise exception 'idempotency_conflict' using errcode='23505'; end;
 perform app.log_audit_event(p_workspace_id,'acquisition_shipment_created','acquisition_shipments',x.id,u,'acquisition.shipment',null,p_source_record_id,null,jsonb_build_object('shipment_public_id',x.public_id,'order_public_id',o.public_id,'status',x.status)); return jsonb_build_object('shipmentPublicId',x.public_id,'status',x.status,'replayed',false); end $$;

create function public.transition_acquisition_shipment(p_workspace_id uuid,p_shipment_public_id text,p_expected_status text,p_new_status text,p_received_at timestamptz default null,p_reason text default null,p_idempotency_key text default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare u uuid; x public.acquisition_shipments%rowtype; reason text:=nullif(btrim(p_reason),''); key text:=btrim(coalesce(p_idempotency_key,'')); fp text; allowed boolean; old text; begin
 u:=app.assert_workspace_role(p_workspace_id,array['owner','operator']::public.workspace_role[]); if char_length(key) not between 8 and 200 then raise exception 'invalid_request' using errcode='22023'; end if; fp:=encode(digest(concat_ws('|',p_expected_status,p_new_status,p_received_at,reason),'sha256'),'hex'); select * into x from public.acquisition_shipments where workspace_id=p_workspace_id and public_id=p_shipment_public_id for update; if x.id is null then raise exception 'shipment_not_found' using errcode='P0002'; end if;
 if x.transition_idempotency_key=key then if x.transition_fingerprint=fp then return jsonb_build_object('shipmentPublicId',x.public_id,'status',x.status,'replayed',true); end if; raise exception 'idempotency_conflict' using errcode='23505'; end if; if x.status::text<>p_expected_status then raise exception 'stale_status' using errcode='40001'; end if; if p_new_status=p_expected_status then return jsonb_build_object('shipmentPublicId',x.public_id,'status',x.status,'replayed',true); end if;
 allowed := (p_expected_status='expected' and p_new_status in ('in_transit','delivered','lost','cancelled')) or (p_expected_status='in_transit' and p_new_status in ('delivered','lost','cancelled')) or (p_expected_status='lost' and p_new_status in ('in_transit','delivered','cancelled')); if not allowed then raise exception 'invalid_transition' using errcode='22023'; end if; if p_new_status in ('lost','cancelled') and reason is null then raise exception 'invalid_request' using errcode='22023'; end if; old:=x.status;
 perform set_config('app.governed_acquisition_mutation','on',true); update public.acquisition_shipments set status=p_new_status::public.acquisition_shipment_status,received_at=case when p_new_status='delivered' then coalesce(p_received_at,now()) else null end,transition_reason=reason,transition_idempotency_key=key,transition_fingerprint=fp,updated_at=now() where id=x.id returning * into x;
 perform app.log_audit_event(p_workspace_id,'acquisition_shipment_transitioned','acquisition_shipments',x.id,u,'acquisition.shipment',null,x.source_record_id,null,jsonb_build_object('shipment_public_id',x.public_id,'old_status',old,'new_status',x.status,'reason',reason)); return jsonb_build_object('shipmentPublicId',x.public_id,'status',x.status,'replayed',false); end $$;

create function public.classify_acquisition_line_by_public_id(p_workspace_id uuid,p_acquisition_line_public_id text) returns jsonb language plpgsql security definer set search_path='' as $$ declare id uuid; begin perform app.assert_workspace_role(p_workspace_id,array['owner','operator']::public.workspace_role[]); select acquisition_line_item_id into id from public.acquisition_line_overview where workspace_id=p_workspace_id and acquisition_line_public_id=p_acquisition_line_public_id; if id is null then raise exception 'acquisition_not_found' using errcode='P0002'; end if; return public.classify_acquisition_line(id); end $$;
create function public.override_acquisition_line_classification_by_public_id(p_workspace_id uuid,p_acquisition_line_public_id text,p_classification_option_key text,p_reason text) returns jsonb language plpgsql security definer set search_path='' as $$ declare id uuid; begin perform app.assert_workspace_role(p_workspace_id,array['owner']::public.workspace_role[]); select acquisition_line_item_id into id from public.acquisition_line_overview where workspace_id=p_workspace_id and acquisition_line_public_id=p_acquisition_line_public_id; if id is null then raise exception 'acquisition_not_found' using errcode='P0002'; end if; return public.override_acquisition_line_classification(id,p_classification_option_key,p_reason); end $$;

create function public.get_acquisition_line_detail(p_workspace_id uuid,p_acquisition_line_public_id text) returns jsonb language plpgsql stable security definer set search_path='' as $$ declare v public.acquisition_line_overview%rowtype; result jsonb; begin perform app.assert_workspace_role(p_workspace_id,array['owner','operator','viewer']::public.workspace_role[]); select * into v from public.acquisition_line_overview where workspace_id=p_workspace_id and acquisition_line_public_id=p_acquisition_line_public_id; if v.acquisition_line_item_id is null then return null; end if;
 select jsonb_build_object('coverage','governed_native_committed','historicalLegacyImported',false,'line',jsonb_build_object('publicId',v.acquisition_line_public_id,'quantity',v.quantity,'description',v.description,'referenceNumber',v.reference_number,'sourceDetail',v.source_detail,'createdAt',v.created_at,'businessVertical',v.business_vertical,'fullTitle',v.full_title,'deliveredItemTitle',v.delivered_item_title,'sellerNormalized',v.seller_normalized),'order',jsonb_build_object('publicId',v.acquisition_order_public_id,'sourceOrderReference',v.source_order_reference,'status',v.order_status,'sourceReportedStatus',v.source_reported_status,'sourceReportedTotalMinor',o.source_reported_total_minor,'currency',o.currency,'occurredAt',v.occurred_at,'channel',jsonb_build_object('publicId',ch.public_id,'name',ch.name),'supplier',jsonb_build_object('publicId',s.public_id,'displayName',s.display_name),'sourceSystem',jsonb_build_object('publicId',ss.public_id,'kind',ss.kind)),'placement',jsonb_build_object('lotPublicId',lot.public_id,'sequence',lot.sequence_no,'label',lot.label,'integrityState',case when lot.id is null then 'missing_active_placement' else 'current' end),
 'classification',case when c.id is null then null else jsonb_build_object('publicId',c.public_id,'optionKey',co.key,'optionLabel',co.label,'method',c.method,'confidence',c.confidence,'createdAt',c.created_at,'state',v.classification_state,'rulePublicId',r.public_id,'ruleLogicalKey',r.logical_key,'ruleVersion',c.rule_version) end,
 'classificationHistory',(select coalesce(jsonb_agg(jsonb_build_object('publicId',h.public_id,'optionKey',ho.key,'optionLabel',ho.label,'method',h.method,'confidence',h.confidence,'createdAt',h.created_at,'supersededAt',h.superseded_at,'ownerOverrideReason',h.evidence->>'owner_reason') order by h.created_at,h.id),'[]') from public.acquisition_line_classifications h join public.acquisition_classification_options ho on ho.id=h.classification_option_id and ho.workspace_id=h.workspace_id where h.workspace_id=p_workspace_id and h.acquisition_line_item_id=v.acquisition_line_item_id),
 'classificationOptions',(select coalesce(jsonb_agg(jsonb_build_object('key',x.key,'label',x.label) order by x.display_order,x.key),'[]') from public.acquisition_classification_options x where x.workspace_id=p_workspace_id and x.active),
 'payments',(select coalesce(jsonb_agg(jsonb_build_object('publicId',p.public_id,'paidAt',p.paid_at,'amountMinor',p.amount_minor,'currency',p.currency,'instrument',p.instrument,'externalReference',p.external_reference,'evidenceNote',p.evidence_note,'state',case when p.reversed_at is null then 'active' else 'reversed' end,'reversedAt',p.reversed_at,'reversalReason',p.reversal_reason) order by p.paid_at,p.created_at),'[]') from public.acquisition_payments p where p.workspace_id=p_workspace_id and p.acquisition_order_id=v.acquisition_order_id),
 'paymentSummary',(select jsonb_build_object('activeCount',count(*) filter(where p.reversed_at is null),'activeCurrencies',coalesce(jsonb_agg(distinct p.currency) filter(where p.reversed_at is null),'[]'),'mixedCurrencies',count(distinct p.currency) filter(where p.reversed_at is null)>1,'activeTotalMinor',case when count(distinct p.currency) filter(where p.reversed_at is null)=1 then sum(p.amount_minor) filter(where p.reversed_at is null) end,'sourceReportedTotalMinor',o.source_reported_total_minor,'differenceMinor',case when count(distinct p.currency) filter(where p.reversed_at is null)=1 and min(p.currency) filter(where p.reversed_at is null)=o.currency then o.source_reported_total_minor-sum(p.amount_minor) filter(where p.reversed_at is null) end) from public.acquisition_payments p where p.workspace_id=p_workspace_id and p.acquisition_order_id=v.acquisition_order_id),
 'shipments',(select coalesce(jsonb_agg(jsonb_build_object('publicId',sh.public_id,'carrier',sh.carrier,'trackingNumber',sh.tracking_number,'status',sh.status,'shippedAt',sh.shipped_at,'expectedAt',sh.expected_at,'receivedAt',sh.received_at,'shippingReferenceMinor',sh.shipping_cost_minor,'currency',sh.currency,'evidenceNote',sh.evidence_note,'allowedNextTransitions',case sh.status when 'expected' then '["in_transit","delivered","lost","cancelled"]'::jsonb when 'in_transit' then '["delivered","lost","cancelled"]'::jsonb when 'lost' then '["in_transit","delivered","cancelled"]'::jsonb else '[]'::jsonb end) order by sh.created_at),'[]') from public.acquisition_shipments sh where sh.workspace_id=p_workspace_id and sh.acquisition_order_id=v.acquisition_order_id),
 'sourceEvidence',jsonb_build_object('sourceSystemPublicId',ss.public_id,'sourceRecordId',v.source_record_id,'sourceImportJobId',v.source_import_job_id)) into result
 from public.acquisition_orders o join public.channels ch on ch.id=o.channel_id and ch.workspace_id=o.workspace_id join public.suppliers s on s.id=o.supplier_id and s.workspace_id=o.workspace_id join public.source_systems ss on ss.id=o.source_system_id and ss.workspace_id=o.workspace_id left join public.acquisition_lots lot on lot.order_id=o.id and lot.workspace_id=o.workspace_id left join public.acquisition_lot_lines ll on ll.lot_id=lot.id and ll.workspace_id=lot.workspace_id and ll.line_item_id=v.acquisition_line_item_id and ll.state='active' left join public.acquisition_line_classifications c on c.id=v.classification_id left join public.acquisition_classification_options co on co.id=c.classification_option_id left join public.classification_rules r on r.id=c.rule_id where o.id=v.acquisition_order_id limit 1; return result; end $$;

revoke all on function public.record_acquisition_payment(uuid,text,timestamptz,bigint,text,text,text,uuid,text,text), public.reverse_acquisition_payment(uuid,text,text,text), public.create_acquisition_shipment(uuid,text,text,text,timestamptz,timestamptz,text,bigint,text,uuid,text,text), public.transition_acquisition_shipment(uuid,text,text,text,timestamptz,text,text), public.classify_acquisition_line_by_public_id(uuid,text), public.override_acquisition_line_classification_by_public_id(uuid,text,text,text), public.get_acquisition_line_detail(uuid,text) from public,anon;
grant execute on function public.record_acquisition_payment(uuid,text,timestamptz,bigint,text,text,text,uuid,text,text), public.reverse_acquisition_payment(uuid,text,text,text), public.create_acquisition_shipment(uuid,text,text,text,timestamptz,timestamptz,text,bigint,text,uuid,text,text), public.transition_acquisition_shipment(uuid,text,text,text,timestamptz,text,text), public.classify_acquisition_line_by_public_id(uuid,text), public.override_acquisition_line_classification_by_public_id(uuid,text,text,text), public.get_acquisition_line_detail(uuid,text) to authenticated;
insert into public.schema_migrations_log(migration_name) values('20260806000200_acquisition_payments_shipments_detail');
