-- S1.4 final behavioral acceptance and source-qualified acquisition identity.
-- Existing shipment display evidence normalized by earlier functions cannot be reconstructed without source evidence.

CREATE OR REPLACE FUNCTION public.create_acquisition_shipment(p_workspace_id uuid, p_acquisition_order_public_id text, p_carrier text DEFAULT NULL::text, p_tracking_number text DEFAULT NULL::text, p_shipped_at timestamp with time zone DEFAULT NULL::timestamp with time zone, p_expected_at timestamp with time zone DEFAULT NULL::timestamp with time zone, p_status text DEFAULT 'expected'::text, p_shipping_cost_minor bigint DEFAULT NULL::bigint, p_currency text DEFAULT NULL::text, p_source_record_id uuid DEFAULT NULL::uuid, p_evidence_note text DEFAULT NULL::text, p_idempotency_key text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare u uuid; o public.acquisition_orders%rowtype; x public.acquisition_shipments%rowtype; car text:=nullif(btrim(p_carrier),''); track text:=nullif(btrim(p_tracking_number),''); normalized_car text:=nullif(lower(btrim(p_carrier)),''); normalized_track text:=nullif(lower(regexp_replace(btrim(p_tracking_number),'[[:space:]-]','','g')),''); note text:=nullif(btrim(p_evidence_note),''); key text:=btrim(coalesce(p_idempotency_key,'')); cur text:=nullif(upper(btrim(p_currency)),''); fp text; recv timestamptz;
begin
 u:=app.assert_workspace_role(p_workspace_id,array['owner','operator']::public.workspace_role[]); if p_status not in ('expected','in_transit') then raise exception 'invalid_initial_status' using errcode='22023'; end if; if char_length(key) not between 8 and 200 or char_length(coalesce(car,''))>100 or char_length(coalesce(track,''))>200 or char_length(coalesce(note,''))>1000 then raise exception 'invalid_request' using errcode='22023'; end if;
 if p_shipping_cost_minor is not null and p_shipping_cost_minor<0 then raise exception 'invalid_shipping_reference_amount' using errcode='22023'; end if; if (p_shipping_cost_minor is null)<>(cur is null) or (cur is not null and cur !~ '^[A-Z]{3}$') then raise exception 'invalid_currency' using errcode='22023'; end if; if p_expected_at is not null and p_shipped_at is not null and p_expected_at<p_shipped_at then raise exception 'invalid_request' using errcode='22023'; end if;
 select a.* into o from public.acquisition_orders a join public.acquisition_import_jobs j on j.id=a.acquisition_import_job_id and j.workspace_id=a.workspace_id and j.status='committed' where a.workspace_id=p_workspace_id and a.public_id=p_acquisition_order_public_id; if o.id is null then raise exception 'acquisition_not_found' using errcode='P0002'; end if;
 if p_source_record_id is not null and not exists(select 1 from public.source_records s where s.id=p_source_record_id and s.workspace_id=p_workspace_id) then raise exception 'invalid_source_evidence' using errcode='22023'; end if;
 recv:=null; fp:=encode(digest(jsonb_build_object('order_id',o.id,'carrier',normalized_car,'tracking_number',normalized_track,'shipped_at',p_shipped_at,'expected_at',p_expected_at,'status',p_status,'shipping_cost_minor',p_shipping_cost_minor,'currency',cur,'source_record_id',p_source_record_id,'evidence_note',note)::text,'sha256'),'hex');
 perform pg_advisory_xact_lock(hashtextextended(p_workspace_id::text||':'||key,0)); select * into x from public.acquisition_shipments where workspace_id=p_workspace_id and create_idempotency_key=key; if x.id is not null then if x.create_fingerprint<>fp then raise exception 'idempotency_conflict' using errcode='23505'; end if; return jsonb_build_object('shipmentPublicId',x.public_id,'status',x.status,'replayed',true); end if;
 begin insert into public.acquisition_shipments(workspace_id,acquisition_order_id,carrier,tracking_number,shipped_at,expected_at,received_at,status,shipping_cost_minor,currency,source_record_id,evidence_note,create_idempotency_key,create_fingerprint,created_by) values(p_workspace_id,o.id,car,track,p_shipped_at,p_expected_at,recv,p_status::public.acquisition_shipment_status,p_shipping_cost_minor,cur,p_source_record_id,note,key,fp,u) returning * into x; exception when unique_violation then if car is not null and track is not null and exists(select 1 from public.acquisition_shipments s where s.workspace_id=p_workspace_id and lower(btrim(s.carrier))=normalized_car and lower(regexp_replace(btrim(s.tracking_number),'[[:space:]-]','','g'))=normalized_track) then raise exception 'duplicate_tracking' using errcode='23505'; end if; raise exception 'idempotency_conflict' using errcode='23505'; end;
 perform app.log_audit_event(p_workspace_id,'acquisition_shipment_created','acquisition_shipments',x.id,u,'acquisition.shipment',null,p_source_record_id,null,jsonb_build_object('shipment_public_id',x.public_id,'order_public_id',o.public_id,'status',x.status)); return jsonb_build_object('shipmentPublicId',x.public_id,'status',x.status,'replayed',false);
end $function$;

CREATE OR REPLACE FUNCTION public.get_acquisition_line_detail_by_source(p_workspace_id uuid, p_source_system_public_id text, p_acquisition_line_public_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$ declare v public.acquisition_line_overview%rowtype; result jsonb; match_count integer; placement_count integer; begin perform app.assert_workspace_role(p_workspace_id,array['owner','operator','viewer']::public.workspace_role[]); select count(distinct acquisition_line_item_id) into match_count from public.acquisition_line_overview where workspace_id=p_workspace_id and source_system_public_id=p_source_system_public_id and acquisition_line_public_id=p_acquisition_line_public_id; if match_count=0 then return null; end if; if match_count>1 then raise exception 'acquisition_integrity_error' using errcode='23514'; end if; select * into v from public.acquisition_line_overview where workspace_id=p_workspace_id and source_system_public_id=p_source_system_public_id and acquisition_line_public_id=p_acquisition_line_public_id; select count(*) into placement_count from public.acquisition_lot_lines where workspace_id=p_workspace_id and line_item_id=v.acquisition_line_item_id and state='active'; if placement_count>1 then raise exception 'acquisition_integrity_error' using errcode='23514'; end if;
 select jsonb_build_object('coverage','governed_native_committed','historicalLegacyImported',false,'identity',jsonb_build_object('sourceSystemPublicId',v.source_system_public_id,'linePublicId',v.acquisition_line_public_id),'line',jsonb_build_object('publicId',v.acquisition_line_public_id,'quantity',v.quantity,'description',v.description,'referenceNumber',v.reference_number,'sourceDetail',v.source_detail,'createdAt',v.created_at,'businessVertical',v.business_vertical,'fullTitle',v.full_title,'deliveredItemTitle',v.delivered_item_title,'sellerNormalized',v.seller_normalized),'order',jsonb_build_object('publicId',v.acquisition_order_public_id,'sourceOrderReference',v.source_order_reference,'status',v.order_status,'sourceReportedStatus',v.source_reported_status,'sourceReportedTotalMinor',o.source_reported_total_minor,'currency',o.currency,'occurredAt',v.occurred_at,'channel',jsonb_build_object('publicId',ch.public_id,'name',ch.name),'supplier',jsonb_build_object('publicId',s.public_id,'displayName',s.display_name),'sourceSystem',jsonb_build_object('publicId',ss.public_id,'kind',ss.kind)),'placement',jsonb_build_object('lotPublicId',lot.public_id,'sequence',lot.sequence_no,'label',lot.label,'integrityState',case when lot.id is null then 'missing_active_placement' else 'current' end),
 'classification',case when c.id is null then null else jsonb_build_object('publicId',c.public_id,'optionKey',co.key,'optionLabel',co.label,'method',c.method,'confidence',c.confidence,'createdAt',c.created_at,'state',v.classification_state,'rulePublicId',r.public_id,'ruleLogicalKey',r.logical_key,'ruleVersion',c.rule_version) end,
 'classificationHistory',(select coalesce(jsonb_agg(jsonb_build_object('publicId',h.public_id,'optionKey',ho.key,'optionLabel',ho.label,'method',h.method,'confidence',h.confidence,'createdAt',h.created_at,'supersededAt',h.superseded_at,'ownerOverrideReason',h.evidence->>'owner_reason') order by h.created_at,h.id),'[]') from public.acquisition_line_classifications h join public.acquisition_classification_options ho on ho.id=h.classification_option_id and ho.workspace_id=h.workspace_id where h.workspace_id=p_workspace_id and h.acquisition_line_item_id=v.acquisition_line_item_id),
 'classificationOptions',(select coalesce(jsonb_agg(jsonb_build_object('key',x.key,'label',x.label) order by x.display_order,x.key),'[]') from public.acquisition_classification_options x where x.workspace_id=p_workspace_id and x.active),
 'payments',(select coalesce(jsonb_agg(jsonb_build_object('publicId',p.public_id,'paidAt',p.paid_at,'amountMinor',p.amount_minor,'currency',p.currency,'instrument',p.instrument,'externalReference',p.external_reference,'evidenceNote',p.evidence_note,'state',case when p.reversed_at is null then 'active' else 'reversed' end,'reversedAt',p.reversed_at,'reversalReason',p.reversal_reason,'reversalEvent',case when pr.id is null then null else jsonb_build_object('publicId',pr.public_id,'actorId',pr.reversed_by,'reversedAt',pr.reversed_at,'reason',pr.reason) end) order by p.paid_at,p.created_at),'[]') from public.acquisition_payments p left join public.acquisition_payment_reversals pr on pr.id=p.reversal_event_id and pr.workspace_id=p.workspace_id where p.workspace_id=p_workspace_id and p.acquisition_order_id=v.acquisition_order_id),
 'paymentSummary',(select jsonb_build_object('activeCount',count(*) filter(where p.reversed_at is null),'activeCurrencies',coalesce(jsonb_agg(distinct p.currency) filter(where p.reversed_at is null),'[]'),'mixedCurrencies',count(distinct p.currency) filter(where p.reversed_at is null)>1,'activeTotalMinor',case when count(distinct p.currency) filter(where p.reversed_at is null)=1 then sum(p.amount_minor) filter(where p.reversed_at is null) end,'sourceReportedTotalMinor',o.source_reported_total_minor,'differenceMinor',case when count(distinct p.currency) filter(where p.reversed_at is null)=1 and min(p.currency) filter(where p.reversed_at is null)=o.currency then o.source_reported_total_minor-sum(p.amount_minor) filter(where p.reversed_at is null) end) from public.acquisition_payments p where p.workspace_id=p_workspace_id and p.acquisition_order_id=v.acquisition_order_id),
 'shipments',(select coalesce(jsonb_agg(jsonb_build_object('publicId',sh.public_id,'carrier',sh.carrier,'trackingNumber',sh.tracking_number,'status',sh.status,'shippedAt',sh.shipped_at,'expectedAt',sh.expected_at,'receivedAt',sh.received_at,'shippingReferenceMinor',sh.shipping_cost_minor,'currency',sh.currency,'evidenceNote',sh.evidence_note,'transitionHistory',(select coalesce(jsonb_agg(jsonb_build_object('publicId',t.public_id,'fromStatus',t.from_status,'toStatus',t.to_status,'applied',t.applied,'receivedAt',t.received_at,'reason',t.reason,'actorId',t.transitioned_by,'createdAt',t.created_at) order by t.created_at,t.id),'[]') from public.acquisition_shipment_transitions t where t.workspace_id=sh.workspace_id and t.acquisition_shipment_id=sh.id),'allowedNextTransitions',case sh.status when 'expected' then '["in_transit","delivered","lost","cancelled"]'::jsonb when 'in_transit' then '["delivered","lost","cancelled"]'::jsonb when 'lost' then '["in_transit","delivered","cancelled"]'::jsonb else '[]'::jsonb end) order by sh.created_at),'[]') from public.acquisition_shipments sh where sh.workspace_id=p_workspace_id and sh.acquisition_order_id=v.acquisition_order_id),
 'sourceEvidence',jsonb_build_object('sourceSystemPublicId',ss.public_id,'sourceRecordPublicIdentity',(select sr.source_row_key from public.source_records sr where sr.id=v.source_record_id),'acquisitionImportPublicIdentity',(select ij.public_id from public.import_jobs ij join public.acquisition_import_jobs aj on aj.source_import_job_id=ij.id where aj.id=v.acquisition_import_job_id))) into result
 from public.acquisition_orders o join public.channels ch on ch.id=o.channel_id and ch.workspace_id=o.workspace_id join public.suppliers s on s.id=o.supplier_id and s.workspace_id=o.workspace_id join public.source_systems ss on ss.id=o.source_system_id and ss.workspace_id=o.workspace_id left join public.acquisition_lot_lines ll on ll.line_item_id=v.acquisition_line_item_id and ll.workspace_id=p_workspace_id and ll.state='active' left join public.acquisition_lots lot on lot.id=ll.lot_id and lot.workspace_id=ll.workspace_id left join public.acquisition_line_classifications c on c.id=v.classification_id left join public.acquisition_classification_options co on co.id=c.classification_option_id left join public.classification_rules r on r.id=c.rule_id where o.id=v.acquisition_order_id limit 1; return result; end $function$;


create or replace function public.classify_acquisition_line_by_source(p_workspace_id uuid,p_source_system_public_id text,p_acquisition_line_public_id text) returns jsonb language plpgsql security definer set search_path='' as $$ declare line_id uuid; n integer; begin
 perform app.assert_workspace_role(p_workspace_id,array['owner','operator']::public.workspace_role[]);
 select count(distinct acquisition_line_item_id),min(acquisition_line_item_id) into n,line_id from public.acquisition_line_overview where workspace_id=p_workspace_id and source_system_public_id=p_source_system_public_id and acquisition_line_public_id=p_acquisition_line_public_id;
 if n=0 then raise exception 'acquisition_not_found' using errcode='P0002'; elsif n>1 then raise exception 'acquisition_integrity_error' using errcode='23514'; end if;
 return public.classify_acquisition_line(line_id);
end $$;
create or replace function public.override_acquisition_line_classification_by_source(p_workspace_id uuid,p_source_system_public_id text,p_acquisition_line_public_id text,p_classification_option_key text,p_reason text) returns jsonb language plpgsql security definer set search_path='' as $$ declare line_id uuid; n integer; begin
 perform app.assert_workspace_role(p_workspace_id,array['owner']::public.workspace_role[]);
 select count(distinct acquisition_line_item_id),min(acquisition_line_item_id) into n,line_id from public.acquisition_line_overview where workspace_id=p_workspace_id and source_system_public_id=p_source_system_public_id and acquisition_line_public_id=p_acquisition_line_public_id;
 if n=0 then raise exception 'acquisition_not_found' using errcode='P0002'; elsif n>1 then raise exception 'acquisition_integrity_error' using errcode='23514'; end if;
 return public.override_acquisition_line_classification(line_id,p_classification_option_key,p_reason);
end $$;
create or replace function public.get_acquisition_line_detail(p_workspace_id uuid,p_acquisition_line_public_id text) returns jsonb language plpgsql stable security definer set search_path='' as $$ declare n integer; source_id text; begin
 perform app.assert_workspace_role(p_workspace_id,array['owner','operator','viewer']::public.workspace_role[]);
 select count(distinct acquisition_line_item_id),min(source_system_public_id) into n,source_id from public.acquisition_line_overview where workspace_id=p_workspace_id and acquisition_line_public_id=p_acquisition_line_public_id;
 if n=0 then return null; elsif n>1 then raise exception 'ambiguous_acquisition_line_id' using errcode='23514'; end if;
 return public.get_acquisition_line_detail_by_source(p_workspace_id,source_id,p_acquisition_line_public_id);
end $$;
create or replace function public.classify_acquisition_line_by_public_id(p_workspace_id uuid,p_acquisition_line_public_id text) returns jsonb language plpgsql security definer set search_path='' as $$ declare n integer; source_id text; begin
 perform app.assert_workspace_role(p_workspace_id,array['owner','operator']::public.workspace_role[]); select count(distinct acquisition_line_item_id),min(source_system_public_id) into n,source_id from public.acquisition_line_overview where workspace_id=p_workspace_id and acquisition_line_public_id=p_acquisition_line_public_id; if n=0 then raise exception 'acquisition_not_found' using errcode='P0002'; elsif n>1 then raise exception 'ambiguous_acquisition_line_id' using errcode='23514'; end if; return public.classify_acquisition_line_by_source(p_workspace_id,source_id,p_acquisition_line_public_id); end $$;
create or replace function public.override_acquisition_line_classification_by_public_id(p_workspace_id uuid,p_acquisition_line_public_id text,p_classification_option_key text,p_reason text) returns jsonb language plpgsql security definer set search_path='' as $$ declare n integer; source_id text; begin
 perform app.assert_workspace_role(p_workspace_id,array['owner']::public.workspace_role[]); select count(distinct acquisition_line_item_id),min(source_system_public_id) into n,source_id from public.acquisition_line_overview where workspace_id=p_workspace_id and acquisition_line_public_id=p_acquisition_line_public_id; if n=0 then raise exception 'acquisition_not_found' using errcode='P0002'; elsif n>1 then raise exception 'ambiguous_acquisition_line_id' using errcode='23514'; end if; return public.override_acquisition_line_classification_by_source(p_workspace_id,source_id,p_acquisition_line_public_id,p_classification_option_key,p_reason); end $$;

revoke all on function public.get_acquisition_line_detail_by_source(uuid,text,text),public.classify_acquisition_line_by_source(uuid,text,text),public.override_acquisition_line_classification_by_source(uuid,text,text,text,text) from public,anon;
grant execute on function public.get_acquisition_line_detail_by_source(uuid,text,text),public.classify_acquisition_line_by_source(uuid,text,text),public.override_acquisition_line_classification_by_source(uuid,text,text,text,text) to authenticated;

insert into public.schema_migrations_log(migration_name) values('20260806000400_acquisition_s1_4_final_acceptance');
