-- S1.4 additive integrity hardening: durable, append-only operation ledgers.
create table public.acquisition_payment_reversals (
 id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete restrict,
 public_id text not null default app.mint_governed_public_id('RV-APREV') check(public_id ~ '^RV-APREV-[A-Z0-9]{6,20}$'),
 acquisition_payment_id uuid not null, reason text not null check(char_length(reason) between 1 and 500),
 idempotency_key text not null check(char_length(idempotency_key) between 8 and 200), payload_fingerprint text not null check(char_length(payload_fingerprint)=64),
 reversed_by uuid not null references auth.users(id), reversed_at timestamptz not null default now(), created_at timestamptz not null default now(),
 unique(id,workspace_id), unique(workspace_id,public_id), unique(workspace_id,acquisition_payment_id), unique(workspace_id,idempotency_key),
 foreign key(acquisition_payment_id,workspace_id) references public.acquisition_payments(id,workspace_id) on delete restrict
);
create table public.acquisition_shipment_transitions (
 id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete restrict,
 public_id text not null default app.mint_governed_public_id('RV-ASTRAN') check(public_id ~ '^RV-ASTRAN-[A-Z0-9]{6,20}$'),
 acquisition_shipment_id uuid not null, from_status public.acquisition_shipment_status not null, to_status public.acquisition_shipment_status not null,
 applied boolean not null, received_at timestamptz, reason text check(reason is null or char_length(reason) between 1 and 500),
 idempotency_key text not null check(char_length(idempotency_key) between 8 and 200), payload_fingerprint text not null check(char_length(payload_fingerprint)=64),
 transitioned_by uuid not null references auth.users(id), created_at timestamptz not null default now(),
 unique(id,workspace_id), unique(workspace_id,public_id), unique(workspace_id,idempotency_key),
 foreign key(acquisition_shipment_id,workspace_id) references public.acquisition_shipments(id,workspace_id) on delete restrict,
 check(not applied or to_status not in ('lost','cancelled') or reason is not null),
 check((to_status='delivered')=(received_at is not null))
);
alter table public.acquisition_payments add column reversal_event_id uuid;
alter table public.acquisition_payments add constraint acquisition_payments_reversal_event_fk foreign key(reversal_event_id,workspace_id) references public.acquisition_payment_reversals(id,workspace_id) on delete restrict;

create trigger acquisition_payment_reversals_guard before update or delete on public.acquisition_payment_reversals for each row execute function app.guard_acquisition_event_rows();
create trigger acquisition_shipment_transitions_guard before update or delete on public.acquisition_shipment_transitions for each row execute function app.guard_acquisition_event_rows();
alter table public.acquisition_payment_reversals enable row level security;
alter table public.acquisition_shipment_transitions enable row level security;
create policy acquisition_payment_reversals_member_read on public.acquisition_payment_reversals for select to authenticated using(exists(select 1 from public.workspace_members m where m.workspace_id=acquisition_payment_reversals.workspace_id and m.user_id=auth.uid()));
create policy acquisition_shipment_transitions_member_read on public.acquisition_shipment_transitions for select to authenticated using(exists(select 1 from public.workspace_members m where m.workspace_id=acquisition_shipment_transitions.workspace_id and m.user_id=auth.uid()));
revoke all on public.acquisition_payment_reversals,public.acquisition_shipment_transitions from public,anon,authenticated;
grant select on public.acquisition_payment_reversals,public.acquisition_shipment_transitions to authenticated;

create or replace function public.record_acquisition_payment(p_workspace_id uuid,p_acquisition_order_public_id text,p_paid_at timestamptz,p_amount_minor bigint,p_currency text,p_instrument text,p_external_reference text default null,p_source_record_id uuid default null,p_evidence_note text default null,p_idempotency_key text default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare u uuid; o public.acquisition_orders%rowtype; x public.acquisition_payments%rowtype; fp text; ext text:=nullif(btrim(p_external_reference),''); note text:=nullif(btrim(p_evidence_note),''); key text:=btrim(coalesce(p_idempotency_key,'')); cur text:=upper(btrim(coalesce(p_currency,'')));
begin
 u:=app.assert_workspace_role(p_workspace_id,array['owner','operator']::public.workspace_role[]);
 if p_paid_at is null or p_amount_minor is null or p_amount_minor<=0 or char_length(key) not between 8 and 200 or char_length(coalesce(ext,''))>200 or char_length(coalesce(note,''))>1000 then raise exception 'invalid_request' using errcode='22023'; end if;
 if cur !~ '^[A-Z]{3}$' then raise exception 'invalid_currency' using errcode='22023'; end if;
 if p_instrument not in ('card','bank','balance','credit','cash','other') then raise exception 'invalid_instrument' using errcode='22023'; end if;
 select a.* into o from public.acquisition_orders a join public.acquisition_import_jobs j on j.id=a.acquisition_import_job_id and j.workspace_id=a.workspace_id and j.status='committed' where a.workspace_id=p_workspace_id and a.public_id=p_acquisition_order_public_id;
 if o.id is null then raise exception 'acquisition_not_found' using errcode='P0002'; end if;
 if p_source_record_id is not null and not exists(select 1 from public.source_records s where s.id=p_source_record_id and s.workspace_id=p_workspace_id) then raise exception 'invalid_source_evidence' using errcode='22023'; end if;
 fp:=encode(digest(jsonb_build_object('order_id',o.id,'paid_at',p_paid_at,'amount_minor',p_amount_minor,'currency',cur,'instrument',p_instrument,'external_reference',ext,'source_record_id',p_source_record_id,'evidence_note',note)::text,'sha256'),'hex');
 perform pg_advisory_xact_lock(hashtextextended(p_workspace_id::text||':'||key,0)); select * into x from public.acquisition_payments where workspace_id=p_workspace_id and idempotency_key=key;
 if x.id is not null then if x.payload_fingerprint<>fp then raise exception 'idempotency_conflict' using errcode='23505'; end if; return jsonb_build_object('paymentPublicId',x.public_id,'replayed',true); end if;
 begin insert into public.acquisition_payments(workspace_id,acquisition_order_id,paid_at,amount_minor,currency,instrument,external_reference,source_record_id,evidence_note,idempotency_key,payload_fingerprint,created_by) values(p_workspace_id,o.id,p_paid_at,p_amount_minor,cur,p_instrument::public.acquisition_payment_instrument,ext,p_source_record_id,note,key,fp,u) returning * into x;
 exception when unique_violation then if ext is not null and exists(select 1 from public.acquisition_payments p where p.workspace_id=p_workspace_id and lower(p.external_reference)=lower(ext) and p.reversed_at is null) then raise exception 'duplicate_external_reference' using errcode='23505'; end if; raise exception 'idempotency_conflict' using errcode='23505'; end;
 perform app.log_audit_event(p_workspace_id,'acquisition_payment_recorded','acquisition_payments',x.id,u,'acquisition.payment',null,p_source_record_id,null,jsonb_build_object('payment_public_id',x.public_id,'order_public_id',o.public_id,'amount_minor',p_amount_minor,'currency',cur));
 return jsonb_build_object('paymentPublicId',x.public_id,'replayed',false);
end $$;

create or replace function public.reverse_acquisition_payment(p_workspace_id uuid,p_payment_public_id text,p_reason text,p_idempotency_key text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare u uuid; x public.acquisition_payments%rowtype; e public.acquisition_payment_reversals%rowtype; reason text:=btrim(coalesce(p_reason,'')); key text:=btrim(coalesce(p_idempotency_key,'')); fp text;
begin
 u:=app.assert_workspace_role(p_workspace_id,array['owner']::public.workspace_role[]); if char_length(reason) not between 1 and 500 or char_length(key) not between 8 and 200 then raise exception 'invalid_request' using errcode='22023'; end if;
 fp:=encode(digest(jsonb_build_object('payment_public_id',btrim(p_payment_public_id),'reason',reason)::text,'sha256'),'hex'); perform pg_advisory_xact_lock(hashtextextended(p_workspace_id::text||':'||key,0));
 select * into e from public.acquisition_payment_reversals where workspace_id=p_workspace_id and idempotency_key=key; if e.id is not null then if e.payload_fingerprint<>fp then raise exception 'idempotency_conflict' using errcode='23505'; end if; return jsonb_build_object('paymentPublicId',p_payment_public_id,'reversalPublicId',e.public_id,'replayed',true,'state','reversed'); end if;
 select * into x from public.acquisition_payments where workspace_id=p_workspace_id and public_id=p_payment_public_id for update; if x.id is null then raise exception 'payment_not_found' using errcode='P0002'; end if; if x.reversed_at is not null then raise exception 'already_reversed' using errcode='23505'; end if;
 insert into public.acquisition_payment_reversals(workspace_id,acquisition_payment_id,reason,idempotency_key,payload_fingerprint,reversed_by) values(p_workspace_id,x.id,reason,key,fp,u) returning * into e;
 perform set_config('app.governed_acquisition_mutation','on',true); update public.acquisition_payments set reversed_at=e.reversed_at,reversed_by=u,reversal_reason=reason,reversal_idempotency_key=key,reversal_event_id=e.id where id=x.id;
 perform app.log_audit_event(p_workspace_id,'acquisition_payment_reversed','acquisition_payments',x.id,u,'acquisition.payment',null,x.source_record_id,null,jsonb_build_object('payment_public_id',x.public_id,'reversal_public_id',e.public_id,'reason',reason));
 return jsonb_build_object('paymentPublicId',x.public_id,'reversalPublicId',e.public_id,'replayed',false,'state','reversed');
end $$;

create or replace function public.create_acquisition_shipment(p_workspace_id uuid,p_acquisition_order_public_id text,p_carrier text default null,p_tracking_number text default null,p_shipped_at timestamptz default null,p_expected_at timestamptz default null,p_status text default 'expected',p_shipping_cost_minor bigint default null,p_currency text default null,p_source_record_id uuid default null,p_evidence_note text default null,p_idempotency_key text default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare u uuid; o public.acquisition_orders%rowtype; x public.acquisition_shipments%rowtype; car text:=nullif(lower(btrim(p_carrier)),''); track text:=nullif(lower(regexp_replace(btrim(p_tracking_number),'[[:space:]-]','','g')),''); note text:=nullif(btrim(p_evidence_note),''); key text:=btrim(coalesce(p_idempotency_key,'')); cur text:=nullif(upper(btrim(p_currency)),''); fp text; recv timestamptz;
begin
 u:=app.assert_workspace_role(p_workspace_id,array['owner','operator']::public.workspace_role[]); if p_status not in ('expected','in_transit','delivered') then raise exception 'invalid_initial_status' using errcode='22023'; end if; if char_length(key) not between 8 and 200 or char_length(coalesce(car,''))>100 or char_length(coalesce(track,''))>200 or char_length(coalesce(note,''))>1000 then raise exception 'invalid_request' using errcode='22023'; end if;
 if p_shipping_cost_minor is not null and p_shipping_cost_minor<0 then raise exception 'invalid_shipping_reference_amount' using errcode='22023'; end if; if (p_shipping_cost_minor is null)<>(cur is null) or (cur is not null and cur !~ '^[A-Z]{3}$') then raise exception 'invalid_currency' using errcode='22023'; end if; if p_expected_at is not null and p_shipped_at is not null and p_expected_at<p_shipped_at then raise exception 'invalid_request' using errcode='22023'; end if;
 select a.* into o from public.acquisition_orders a join public.acquisition_import_jobs j on j.id=a.acquisition_import_job_id and j.workspace_id=a.workspace_id and j.status='committed' where a.workspace_id=p_workspace_id and a.public_id=p_acquisition_order_public_id; if o.id is null then raise exception 'acquisition_not_found' using errcode='P0002'; end if;
 if p_source_record_id is not null and not exists(select 1 from public.source_records s where s.id=p_source_record_id and s.workspace_id=p_workspace_id) then raise exception 'invalid_source_evidence' using errcode='22023'; end if;
 recv:=case when p_status='delivered' then coalesce(p_expected_at,p_shipped_at,now()) else null end; fp:=encode(digest(jsonb_build_object('order_id',o.id,'carrier',car,'tracking_number',track,'shipped_at',p_shipped_at,'expected_at',p_expected_at,'status',p_status,'shipping_cost_minor',p_shipping_cost_minor,'currency',cur,'source_record_id',p_source_record_id,'evidence_note',note)::text,'sha256'),'hex');
 perform pg_advisory_xact_lock(hashtextextended(p_workspace_id::text||':'||key,0)); select * into x from public.acquisition_shipments where workspace_id=p_workspace_id and create_idempotency_key=key; if x.id is not null then if x.create_fingerprint<>fp then raise exception 'idempotency_conflict' using errcode='23505'; end if; return jsonb_build_object('shipmentPublicId',x.public_id,'status',x.status,'replayed',true); end if;
 begin insert into public.acquisition_shipments(workspace_id,acquisition_order_id,carrier,tracking_number,shipped_at,expected_at,received_at,status,shipping_cost_minor,currency,source_record_id,evidence_note,create_idempotency_key,create_fingerprint,created_by) values(p_workspace_id,o.id,car,track,p_shipped_at,p_expected_at,recv,p_status::public.acquisition_shipment_status,p_shipping_cost_minor,cur,p_source_record_id,note,key,fp,u) returning * into x; exception when unique_violation then if car is not null and track is not null and exists(select 1 from public.acquisition_shipments s where s.workspace_id=p_workspace_id and lower(s.carrier)=car and lower(regexp_replace(s.tracking_number,'[[:space:]-]','','g'))=track) then raise exception 'duplicate_tracking' using errcode='23505'; end if; raise exception 'idempotency_conflict' using errcode='23505'; end;
 perform app.log_audit_event(p_workspace_id,'acquisition_shipment_created','acquisition_shipments',x.id,u,'acquisition.shipment',null,p_source_record_id,null,jsonb_build_object('shipment_public_id',x.public_id,'order_public_id',o.public_id,'status',x.status)); return jsonb_build_object('shipmentPublicId',x.public_id,'status',x.status,'replayed',false);
end $$;

create or replace function public.transition_acquisition_shipment(p_workspace_id uuid,p_shipment_public_id text,p_expected_status text,p_new_status text,p_received_at timestamptz default null,p_reason text default null,p_idempotency_key text default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare u uuid; x public.acquisition_shipments%rowtype; e public.acquisition_shipment_transitions%rowtype; reason text:=nullif(btrim(p_reason),''); key text:=btrim(coalesce(p_idempotency_key,'')); fp text; allowed boolean; recv timestamptz;
begin
 u:=app.assert_workspace_role(p_workspace_id,array['owner','operator']::public.workspace_role[]); if char_length(key) not between 8 and 200 then raise exception 'invalid_request' using errcode='22023'; end if; if p_expected_status not in ('expected','in_transit','delivered','lost','cancelled') or p_new_status not in ('expected','in_transit','delivered','lost','cancelled') then raise exception 'invalid_transition' using errcode='22023'; end if;
 recv:=case when p_new_status='delivered' then p_received_at else null end; if p_new_status='delivered' and recv is null then raise exception 'invalid_request' using errcode='22023'; end if; if p_new_status in ('lost','cancelled') and reason is null then raise exception 'invalid_request' using errcode='22023'; end if;
 fp:=encode(digest(jsonb_build_object('shipment_public_id',btrim(p_shipment_public_id),'expected_status',p_expected_status,'new_status',p_new_status,'received_at',recv,'reason',reason)::text,'sha256'),'hex'); perform pg_advisory_xact_lock(hashtextextended(p_workspace_id::text||':'||key,0));
 select * into e from public.acquisition_shipment_transitions where workspace_id=p_workspace_id and idempotency_key=key; if e.id is not null then if e.payload_fingerprint<>fp then raise exception 'idempotency_conflict' using errcode='23505'; end if; return jsonb_build_object('shipmentPublicId',p_shipment_public_id,'transitionPublicId',e.public_id,'status',e.to_status,'applied',e.applied,'replayed',true); end if;
 select * into x from public.acquisition_shipments where workspace_id=p_workspace_id and public_id=p_shipment_public_id for update; if x.id is null then raise exception 'shipment_not_found' using errcode='P0002'; end if; if x.status::text<>p_expected_status then raise exception 'stale_status' using errcode='40001'; end if;
 if p_new_status=p_expected_status then insert into public.acquisition_shipment_transitions(workspace_id,acquisition_shipment_id,from_status,to_status,applied,received_at,reason,idempotency_key,payload_fingerprint,transitioned_by) values(p_workspace_id,x.id,x.status,x.status,false,case when x.status='delivered' then x.received_at else null end,reason,key,fp,u) returning * into e; return jsonb_build_object('shipmentPublicId',x.public_id,'transitionPublicId',e.public_id,'status',x.status,'applied',false,'replayed',false); end if;
 allowed := (p_expected_status='expected' and p_new_status in ('in_transit','delivered','lost','cancelled')) or (p_expected_status='in_transit' and p_new_status in ('delivered','lost','cancelled')) or (p_expected_status='lost' and p_new_status in ('in_transit','delivered','cancelled')); if not allowed then raise exception 'invalid_transition' using errcode='22023'; end if;
 insert into public.acquisition_shipment_transitions(workspace_id,acquisition_shipment_id,from_status,to_status,applied,received_at,reason,idempotency_key,payload_fingerprint,transitioned_by) values(p_workspace_id,x.id,x.status,p_new_status::public.acquisition_shipment_status,true,recv,reason,key,fp,u) returning * into e;
 perform set_config('app.governed_acquisition_mutation','on',true); update public.acquisition_shipments set status=p_new_status::public.acquisition_shipment_status,received_at=recv,transition_reason=reason,transition_idempotency_key=null,transition_fingerprint=null,updated_at=now() where id=x.id returning * into x;
 perform app.log_audit_event(p_workspace_id,'acquisition_shipment_transitioned','acquisition_shipments',x.id,u,'acquisition.shipment',null,x.source_record_id,null,jsonb_build_object('shipment_public_id',x.public_id,'transition_public_id',e.public_id,'old_status',p_expected_status,'new_status',x.status,'reason',reason)); return jsonb_build_object('shipmentPublicId',x.public_id,'transitionPublicId',e.public_id,'status',x.status,'applied',true,'replayed',false);
end $$;

create or replace function public.get_acquisition_line_detail(p_workspace_id uuid,p_acquisition_line_public_id text) returns jsonb language plpgsql stable security definer set search_path='' as $$ declare v public.acquisition_line_overview%rowtype; result jsonb; begin perform app.assert_workspace_role(p_workspace_id,array['owner','operator','viewer']::public.workspace_role[]); select * into v from public.acquisition_line_overview where workspace_id=p_workspace_id and acquisition_line_public_id=p_acquisition_line_public_id; if v.acquisition_line_item_id is null then return null; end if;
 select jsonb_build_object('coverage','governed_native_committed','historicalLegacyImported',false,'line',jsonb_build_object('publicId',v.acquisition_line_public_id,'quantity',v.quantity,'description',v.description,'referenceNumber',v.reference_number,'sourceDetail',v.source_detail,'createdAt',v.created_at,'businessVertical',v.business_vertical,'fullTitle',v.full_title,'deliveredItemTitle',v.delivered_item_title,'sellerNormalized',v.seller_normalized),'order',jsonb_build_object('publicId',v.acquisition_order_public_id,'sourceOrderReference',v.source_order_reference,'status',v.order_status,'sourceReportedStatus',v.source_reported_status,'sourceReportedTotalMinor',o.source_reported_total_minor,'currency',o.currency,'occurredAt',v.occurred_at,'channel',jsonb_build_object('publicId',ch.public_id,'name',ch.name),'supplier',jsonb_build_object('publicId',s.public_id,'displayName',s.display_name),'sourceSystem',jsonb_build_object('publicId',ss.public_id,'kind',ss.kind)),'placement',jsonb_build_object('lotPublicId',lot.public_id,'sequence',lot.sequence_no,'label',lot.label,'integrityState',case when lot.id is null then 'missing_active_placement' else 'current' end),
 'classification',case when c.id is null then null else jsonb_build_object('publicId',c.public_id,'optionKey',co.key,'optionLabel',co.label,'method',c.method,'confidence',c.confidence,'createdAt',c.created_at,'state',v.classification_state,'rulePublicId',r.public_id,'ruleLogicalKey',r.logical_key,'ruleVersion',c.rule_version) end,
 'classificationHistory',(select coalesce(jsonb_agg(jsonb_build_object('publicId',h.public_id,'optionKey',ho.key,'optionLabel',ho.label,'method',h.method,'confidence',h.confidence,'createdAt',h.created_at,'supersededAt',h.superseded_at,'ownerOverrideReason',h.evidence->>'owner_reason') order by h.created_at,h.id),'[]') from public.acquisition_line_classifications h join public.acquisition_classification_options ho on ho.id=h.classification_option_id and ho.workspace_id=h.workspace_id where h.workspace_id=p_workspace_id and h.acquisition_line_item_id=v.acquisition_line_item_id),
 'classificationOptions',(select coalesce(jsonb_agg(jsonb_build_object('key',x.key,'label',x.label) order by x.display_order,x.key),'[]') from public.acquisition_classification_options x where x.workspace_id=p_workspace_id and x.active),
 'payments',(select coalesce(jsonb_agg(jsonb_build_object('publicId',p.public_id,'paidAt',p.paid_at,'amountMinor',p.amount_minor,'currency',p.currency,'instrument',p.instrument,'externalReference',p.external_reference,'evidenceNote',p.evidence_note,'state',case when p.reversed_at is null then 'active' else 'reversed' end,'reversedAt',p.reversed_at,'reversalReason',p.reversal_reason,'reversalEvent',case when pr.id is null then null else jsonb_build_object('publicId',pr.public_id,'actorId',pr.reversed_by,'reversedAt',pr.reversed_at,'reason',pr.reason) end) order by p.paid_at,p.created_at),'[]') from public.acquisition_payments p left join public.acquisition_payment_reversals pr on pr.id=p.reversal_event_id and pr.workspace_id=p.workspace_id where p.workspace_id=p_workspace_id and p.acquisition_order_id=v.acquisition_order_id),
 'paymentSummary',(select jsonb_build_object('activeCount',count(*) filter(where p.reversed_at is null),'activeCurrencies',coalesce(jsonb_agg(distinct p.currency) filter(where p.reversed_at is null),'[]'),'mixedCurrencies',count(distinct p.currency) filter(where p.reversed_at is null)>1,'activeTotalMinor',case when count(distinct p.currency) filter(where p.reversed_at is null)=1 then sum(p.amount_minor) filter(where p.reversed_at is null) end,'sourceReportedTotalMinor',o.source_reported_total_minor,'differenceMinor',case when count(distinct p.currency) filter(where p.reversed_at is null)=1 and min(p.currency) filter(where p.reversed_at is null)=o.currency then o.source_reported_total_minor-sum(p.amount_minor) filter(where p.reversed_at is null) end) from public.acquisition_payments p where p.workspace_id=p_workspace_id and p.acquisition_order_id=v.acquisition_order_id),
 'shipments',(select coalesce(jsonb_agg(jsonb_build_object('publicId',sh.public_id,'carrier',sh.carrier,'trackingNumber',sh.tracking_number,'status',sh.status,'shippedAt',sh.shipped_at,'expectedAt',sh.expected_at,'receivedAt',sh.received_at,'shippingReferenceMinor',sh.shipping_cost_minor,'currency',sh.currency,'evidenceNote',sh.evidence_note,'transitionHistory',(select coalesce(jsonb_agg(jsonb_build_object('publicId',t.public_id,'fromStatus',t.from_status,'toStatus',t.to_status,'applied',t.applied,'receivedAt',t.received_at,'reason',t.reason,'actorId',t.transitioned_by,'createdAt',t.created_at) order by t.created_at,t.id),'[]') from public.acquisition_shipment_transitions t where t.workspace_id=sh.workspace_id and t.acquisition_shipment_id=sh.id),'allowedNextTransitions',case sh.status when 'expected' then '["in_transit","delivered","lost","cancelled"]'::jsonb when 'in_transit' then '["delivered","lost","cancelled"]'::jsonb when 'lost' then '["in_transit","delivered","cancelled"]'::jsonb else '[]'::jsonb end) order by sh.created_at),'[]') from public.acquisition_shipments sh where sh.workspace_id=p_workspace_id and sh.acquisition_order_id=v.acquisition_order_id),
 'sourceEvidence',jsonb_build_object('sourceSystemPublicId',ss.public_id,'sourceRecordId',v.source_record_id,'sourceImportJobId',v.source_import_job_id)) into result
 from public.acquisition_orders o join public.channels ch on ch.id=o.channel_id and ch.workspace_id=o.workspace_id join public.suppliers s on s.id=o.supplier_id and s.workspace_id=o.workspace_id join public.source_systems ss on ss.id=o.source_system_id and ss.workspace_id=o.workspace_id left join public.acquisition_lot_lines ll on ll.line_item_id=v.acquisition_line_item_id and ll.workspace_id=p_workspace_id and ll.state='active' left join public.acquisition_lots lot on lot.id=ll.lot_id and lot.workspace_id=ll.workspace_id left join public.acquisition_line_classifications c on c.id=v.classification_id left join public.acquisition_classification_options co on co.id=c.classification_option_id left join public.classification_rules r on r.id=c.rule_id where o.id=v.acquisition_order_id limit 1; return result; end $$;

insert into public.schema_migrations_log(migration_name) values('20260806000300_acquisition_payments_shipments_hardening');
